import { q, opener, closer, careCompetencies, type Role } from './shared';

export const careRoles: Role[] = [
  {
    id: 'nurse',
    title: 'Staff Nurse',
    titleAr: 'ممرض / ممرضة',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Mid',
    blurb: 'Ward care, patient safety, escalation and family communication.',
    blurbAr: 'رعاية الجناح وسلامة المرضى والتصعيد والتواصل مع العائلات.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'deteriorating',
        'Tell me about a patient whose condition deteriorated on your shift. What did you do?',
        'حدثني عن مريض تدهورت حالته أثناء نوبتك. ماذا فعلت؟',
        ['problem_solving', 'ownership', 'compliance', 'evidence'],
      ),
      q(
        'family',
        'How do you handle an anxious family member who is questioning the care being given?',
        'كيف تتعامل مع أحد أفراد العائلة القلق الذي يشكك في الرعاية المقدمة؟',
        ['communication', 'compliance', 'ownership'],
        'Show empathy and boundaries — what you can share, and who you involve.',
        'أظهر التعاطف والحدود — ما يمكنك مشاركته ومن تُشرِكه في الأمر.',
      ),
      q(
        'safety_protocol',
        'Describe how you check and administer medication safely.',
        'صف كيف تتحقق من الأدوية وتعطيها بأمان.',
        ['compliance', 'evidence'],
        'Walk through your actual checks step by step.',
        'اشرح فحوصاتك الفعلية خطوة بخطوة.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'caregiver',
    title: 'Caregiver / Home Nurse',
    titleAr: 'مقدم رعاية / ممرض منزلي',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Entry',
    blurb: 'Elderly and home care, daily living support, dignity and family trust.',
    blurbAr: 'رعاية كبار السن والرعاية المنزلية ودعم الحياة اليومية والكرامة وثقة العائلة.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'refusing_care',
        'The person you care for refuses to eat or take their medication. What do you do?',
        'الشخص الذي ترعاه يرفض الأكل أو تناول دوائه. ماذا تفعل؟',
        ['problem_solving', 'compliance', 'communication', 'ownership'],
        'Show patience and respect for their choice, and say when you would call the family or doctor.',
        'أظهر الصبر واحترام اختياره، ووضّح متى ستتصل بالعائلة أو الطبيب.',
      ),
      q(
        'dignity',
        'How do you protect someone’s dignity when helping them with personal care?',
        'كيف تحافظ على كرامة الشخص عند مساعدته في الرعاية الشخصية؟',
        ['compliance', 'communication', 'customer_focus'],
      ),
      q(
        'emergency_home',
        'You find the person you care for on the floor. Walk me through what you do.',
        'تجد الشخص الذي ترعاه على الأرض. اشرح لي ماذا ستفعل.',
        ['problem_solving', 'ownership', 'compliance'],
        'Give your steps in order. Calm and correct sequence is what is being scored.',
        'اذكر خطواتك بالترتيب. الهدوء والتسلسل الصحيح هو ما يُقيَّم.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'pharmacy-assistant',
    title: 'Pharmacist / Pharmacy Assistant',
    titleAr: 'صيدلي / مساعد صيدلي',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Mid',
    blurb: 'Dispensing, prescription checks, customer advice and controlled medicines.',
    blurbAr: 'صرف الأدوية والتحقق من الوصفات ونصح العملاء والأدوية الخاضعة للرقابة.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'prescription_error',
        'You think a prescription may be wrong. What do you do?',
        'تعتقد أن هناك خطأ في وصفة طبية. ماذا تفعل؟',
        ['compliance', 'ownership', 'problem_solving', 'evidence'],
      ),
      q(
        'customer_advice',
        'A customer asks for a medicine that needs a prescription and they do not have one. What do you say?',
        'يطلب عميل دواءً يحتاج وصفة طبية وليست لديه. ماذا تقول؟',
        ['compliance', 'communication', 'customer_focus'],
        'Show that you hold the line, and that you still help the person in front of you.',
        'أظهر أنك متمسك بالقاعدة، وأنك ما زلت تساعد الشخص أمامك.',
      ),
      q(
        'stock_meds',
        'How do you manage expiry dates and storage of medicines?',
        'كيف تدير تواريخ الصلاحية وتخزين الأدوية؟',
        ['compliance', 'evidence'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'nanny',
    title: 'Nanny / Domestic Helper',
    titleAr: 'مربية / عاملة منزلية',
    industry: 'Domestic & Household',
    industryAr: 'العمل المنزلي',
    level: 'Entry',
    blurb: 'Childcare, household routines, safety at home and family communication.',
    blurbAr: 'رعاية الأطفال وروتين المنزل والسلامة المنزلية والتواصل مع العائلة.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'child_safety',
        'A child in your care has an accident at home. Walk me through what you do.',
        'يتعرض طفل في رعايتك لحادث في المنزل. اشرح لي ماذا ستفعل.',
        ['problem_solving', 'ownership', 'compliance'],
        'Give your steps in order, including when and how you tell the parents.',
        'اذكر خطواتك بالترتيب، بما في ذلك متى وكيف تخبرين الوالدين.',
      ),
      q(
        'discipline',
        'A child refuses to listen to you. How do you handle it?',
        'يرفض طفل الاستماع إليك. كيف تتعاملين مع ذلك؟',
        ['communication', 'compliance', 'problem_solving'],
      ),
      q(
        'family_expectations',
        'The family asks you to do something you were not hired for. What do you do?',
        'تطلب منك العائلة القيام بعمل لم تُوظَّفي من أجله. ماذا تفعلين؟',
        ['communication', 'ownership'],
        'Show that you can be helpful and still be clear about what was agreed.',
        'أظهري أنه يمكنك التعاون مع البقاء واضحة بشأن ما تم الاتفاق عليه.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'medical-receptionist',
    title: 'Medical Receptionist',
    titleAr: 'موظف استقبال طبي',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Entry',
    blurb: 'Clinic front desk, appointments, insurance approvals and anxious patients.',
    blurbAr: 'استقبال العيادة والمواعيد وموافقات التأمين والمرضى القلقين.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'insurance_refused',
        'A patient’s insurance is refused at the desk and they are upset. What do you do?',
        'يُرفض تأمين مريض عند الاستقبال وهو منزعج. ماذا تفعل؟',
        ['communication', 'problem_solving', 'ownership'],
        'Insurance problems are daily in Gulf clinics. Show calm and a clear next step.',
        'مشاكل التأمين يومية في عيادات الخليج. أظهر الهدوء وخطوة تالية واضحة.',
      ),
      q(
        'patient_privacy',
        'Someone asks you about another patient’s appointment or condition. How do you respond?',
        'يسألك أحدهم عن موعد أو حالة مريض آخر. كيف ترد؟',
        ['compliance', 'communication', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      q(
        'waiting_room',
        'The doctor is running an hour late and the waiting room is full. What do you do?',
        'الطبيب متأخر ساعة وغرفة الانتظار ممتلئة. ماذا تفعل؟',
        ['problem_solving', 'communication', 'compliance'],
      ),
      closer,
    ],
  },
  {
    id: 'lab-technician',
    title: 'Laboratory Technician',
    titleAr: 'فني مختبر',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Mid',
    blurb: 'Sample handling, testing, quality control and reporting critical results.',
    blurbAr: 'التعامل مع العينات والفحوصات وضبط الجودة والإبلاغ عن النتائج الحرجة.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'sample_integrity',
        'A sample arrives incorrectly labelled or in the wrong tube. What do you do?',
        'تصل عينة بملصق خاطئ أو في أنبوب غير صحيح. ماذا تفعل؟',
        ['compliance', 'ownership', 'problem_solving'],
        'Rejecting a bad sample is the right answer. Show how you handle it professionally.',
        'رفض العينة غير الصالحة هو الإجابة الصحيحة. أظهر كيف تتعامل مع الأمر بمهنية.',
      ),
      q(
        'critical_result',
        'You get a critical result. Walk me through what happens next.',
        'تحصل على نتيجة حرجة. اشرح لي ماذا يحدث بعد ذلك.',
        ['compliance', 'communication', 'ownership', 'evidence'],
      ),
      q(
        'quality_control',
        'How do you run and interpret quality control in your lab?',
        'كيف تُجري وتفسّر ضبط الجودة في مختبرك؟',
        ['evidence', 'compliance'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'radiographer',
    title: 'Radiographer / X-ray Technician',
    titleAr: 'فني أشعة',
    industry: 'Healthcare',
    industryAr: 'الرعاية الصحية',
    level: 'Mid',
    blurb: 'Imaging, patient positioning, radiation protection and nervous patients.',
    blurbAr: 'التصوير وتوضيع المريض والوقاية من الإشعاع والمرضى القلقين.',
    competencies: careCompetencies,
    questions: [
      opener,
      q(
        'radiation_safety',
        'How do you protect the patient, yourself and others from unnecessary radiation?',
        'كيف تحمي المريض ونفسك والآخرين من التعرض غير الضروري للإشعاع؟',
        ['compliance', 'evidence', 'ownership'],
        'Name your real practices — shielding, collimation, checking pregnancy status.',
        'اذكر ممارساتك الحقيقية — الدروع والتحديد والتحقق من احتمال الحمل.',
      ),
      q(
        'difficult_positioning',
        'A patient is in pain and cannot hold the position you need. What do you do?',
        'مريض يتألم ولا يستطيع الثبات في الوضعية التي تحتاجها. ماذا تفعل؟',
        ['problem_solving', 'communication', 'compliance'],
      ),
      q(
        'repeat_image',
        'Tell me about a time you had to repeat an image. Why, and what did you learn?',
        'حدثني عن مرة اضطررت لإعادة صورة. لماذا، وماذا تعلمت؟',
        ['ownership', 'evidence', 'problem_solving'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
];
