import { q, opener, closer, serviceCompetencies, type Role } from './shared';

export const creativeRoles: Role[] = [
  {
    id: 'marketing-executive',
    title: 'Marketing Executive',
    titleAr: 'تنفيذي تسويق',
    industry: 'Marketing & Creative',
    industryAr: 'التسويق والإبداع',
    level: 'Mid',
    blurb: 'Campaigns, social media, agencies and reporting on what actually worked.',
    blurbAr: 'الحملات ووسائل التواصل والوكالات وتقارير ما نجح فعلاً.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'campaign_results',
        'Tell me about a campaign you ran. What did it achieve?',
        'حدثني عن حملة نفّذتها. ماذا حققت؟',
        ['evidence', 'ownership', 'problem_solving'],
        'Give the real numbers: reach, engagement, leads, cost, and what you would change.',
        'اذكر الأرقام الحقيقية: الوصول والتفاعل والعملاء المحتملون والتكلفة, وما ستغيّره.',
        30,
        150,
      ),
      q(
        'campaign_failed',
        'Tell me about a campaign that did not work. Why not?',
        'حدثني عن حملة لم تنجح. لماذا؟',
        ['ownership', 'problem_solving', 'evidence'],
      ),
      q(
        'gulf_audience',
        'How would you adapt a campaign for a Gulf audience?',
        'كيف تكيّف حملة لتناسب جمهور الخليج؟',
        ['customer_focus', 'communication', 'evidence'],
        'Show that you have thought about language, culture, timing and local platforms.',
        'أظهر أنك فكرت في اللغة والثقافة والتوقيت والمنصات المحلية.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'graphic-designer',
    title: 'Graphic Designer',
    titleAr: 'مصمم جرافيك',
    industry: 'Marketing & Creative',
    industryAr: 'التسويق والإبداع',
    level: 'Mid',
    blurb: 'Brand work, bilingual layouts, client feedback and deadlines.',
    blurbAr: 'أعمال الهوية والتصاميم ثنائية اللغة وملاحظات العملاء والمواعيد النهائية.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'design_brief',
        'Walk me through a piece of work from the brief to the final file.',
        'اشرح لي عملاً من الفكرة الأولى حتى الملف النهائي.',
        ['evidence', 'communication', 'problem_solving'],
        'Talk about the decisions you made and why, not just the software you used.',
        'تحدث عن القرارات التي اتخذتها ولماذا، وليس فقط عن البرامج التي استخدمتها.',
        30,
        150,
      ),
      q(
        'client_rejects',
        'A client rejects your work and cannot explain what they want. What do you do?',
        'يرفض العميل عملك ولا يستطيع شرح ما يريده. ماذا تفعل؟',
        ['communication', 'problem_solving', 'customer_focus'],
      ),
      q(
        'bilingual_design',
        'How do you handle a design that has to work in both Arabic and English?',
        'كيف تتعامل مع تصميم يجب أن يعمل بالعربية والإنجليزية معاً؟',
        ['evidence', 'communication', 'customer_focus'],
        'This comes up in almost every Gulf design job. Be specific about type and layout.',
        'يتكرر هذا في معظم وظائف التصميم في الخليج. كن محدداً بشأن الخطوط والتخطيط.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'photographer',
    title: 'Photographer / Videographer',
    titleAr: 'مصور فوتوغرافي / مصور فيديو',
    industry: 'Marketing & Creative',
    industryAr: 'التسويق والإبداع',
    level: 'Mid',
    blurb: 'Shoots, clients on set, difficult conditions, editing and delivery deadlines.',
    blurbAr: 'التصوير والعملاء في الموقع والظروف الصعبة والمونتاج ومواعيد التسليم.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'shoot_wrong',
        'Tell me about a shoot where something went wrong. What did you do?',
        'حدثني عن تصوير حدث فيه خطأ. ماذا فعلت؟',
        ['problem_solving', 'ownership', 'evidence'],
        'Gear failure, bad light, a late client: say what you actually did to save it.',
        'عطل في المعدات أو إضاءة سيئة أو عميل متأخر: اذكر ما فعلته فعلاً لإنقاذ الموقف.',
      ),
      q(
        'directing_people',
        'How do you get a natural result from someone who is uncomfortable on camera?',
        'كيف تحصل على نتيجة طبيعية من شخص غير مرتاح أمام الكاميرا؟',
        ['customer_focus', 'communication', 'evidence'],
      ),
      q(
        'delivery_deadline',
        'A client wants the edit faster than you can properly deliver it. What do you say?',
        'يريد العميل المونتاج أسرع مما يمكنك تسليمه بجودة. ماذا تقول؟',
        ['communication', 'ownership', 'problem_solving'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
];
