import {
  q,
  opener,
  closer,
  serviceCompetencies,
  technicalCompetencies,
  type Role,
} from './shared';

export const hospitalityRoles: Role[] = [
  {
    id: 'front-office-agent',
    title: 'Front Office Agent',
    titleAr: 'موظف استقبال',
    industry: 'Hospitality',
    industryAr: 'الضيافة',
    level: 'Entry',
    blurb: 'Hotel reception, check-in, guest requests and complaint handling.',
    blurbAr: 'استقبال الفندق وتسجيل الوصول وطلبات النزلاء والتعامل مع الشكاوى.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'angry_guest',
        'Tell me about a time an angry guest complained directly to you. What happened?',
        'حدثني عن موقف اشتكى فيه نزيل غاضب لك مباشرة. ماذا حدث؟',
        ['customer_focus', 'ownership', 'problem_solving', 'evidence'],
      ),
      q(
        'overbooking',
        'A guest arrives at 11pm and their room is not ready. Walk me through exactly what you do.',
        'يصل نزيل الساعة ١١ مساءً وغرفته غير جاهزة. اشرح لي بالضبط ماذا ستفعل.',
        ['problem_solving', 'communication', 'customer_focus'],
        'Walk through your steps in order. Say what you would decide yourself and when you would escalate.',
        'اشرح خطواتك بالترتيب. وضّح ما ستقرره بنفسك ومتى ستصعّد الأمر.',
      ),
      q(
        'systems',
        'Which hotel systems have you used, and what did you do in them day to day?',
        'ما أنظمة الفنادق التي استخدمتها، وماذا كنت تفعل بها يومياً؟',
        ['evidence', 'communication'],
        'Name the actual systems (Opera, Protel, Cloudbeds…) and the tasks you did in them.',
        'اذكر الأنظمة الفعلية (أوبرا، بروتيل، كلاودبيدز…) والمهام التي قمت بها.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'waiter',
    title: 'Waiter / Server',
    titleAr: 'نادل',
    industry: 'Food & Beverage',
    industryAr: 'الأغذية والمشروبات',
    level: 'Entry',
    blurb: 'Restaurant service, upselling, food safety and busy-shift pressure.',
    blurbAr: 'خدمة المطاعم والبيع الإضافي وسلامة الغذاء وضغط النوبات المزدحمة.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'wrong_order',
        'A guest says their food is wrong and they are already upset. What do you do?',
        'يقول أحد الضيوف إن طلبه خاطئ وهو منزعج بالفعل. ماذا تفعل؟',
        ['customer_focus', 'ownership', 'problem_solving'],
      ),
      q(
        'upselling',
        'Tell me about a time you successfully recommended something extra to a guest.',
        'حدثني عن مرة نجحت فيها في اقتراح شيء إضافي على أحد الضيوف.',
        ['customer_focus', 'evidence', 'communication'],
      ),
      q(
        'busy_shift',
        'You have six tables seated at once and you are alone on the floor. How do you handle it?',
        'لديك ست طاولات في وقت واحد وأنت وحدك في الصالة. كيف تتعامل مع ذلك؟',
        ['problem_solving', 'ownership', 'communication'],
        'Show how you prioritise, and what you tell the guests while they wait.',
        'أظهر كيف ترتب أولوياتك، وماذا تقول للضيوف أثناء انتظارهم.',
      ),
      closer,
    ],
  },
  {
    id: 'housekeeping-attendant',
    title: 'Housekeeping Attendant',
    titleAr: 'عامل تدبير فندقي',
    industry: 'Hospitality',
    industryAr: 'الضيافة',
    level: 'Entry',
    blurb: 'Room cleaning, guest privacy, lost property and daily room targets.',
    blurbAr: 'تنظيف الغرف وخصوصية النزلاء والمفقودات وأهداف الغرف اليومية.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'room_standard',
        'Walk me through how you clean a guest room from the moment you knock on the door.',
        'اشرح لي كيف تنظّف غرفة نزيل من لحظة طرقك على الباب.',
        ['evidence', 'communication', 'customer_focus'],
        'Give the real order of your steps. Interviewers are listening for method, not speed.',
        'اذكر ترتيب خطواتك الحقيقي. المُحاور يستمع للمنهجية وليس للسرعة.',
      ),
      q(
        'guest_belongings',
        'You find money and jewellery left in a room. What do you do?',
        'تجد نقوداً ومجوهرات متروكة في غرفة. ماذا تفعل؟',
        ['ownership', 'customer_focus', 'communication'],
        'Honesty and following procedure are the whole answer here. Be specific about who you tell.',
        'الأمانة واتباع الإجراءات هما الإجابة كاملة هنا. حدّد بدقة من ستُبلغ.',
        20,
        90,
      ),
      q(
        'time_pressure',
        'You have 15 rooms to finish and a guest asks you to clean theirs immediately. What do you do?',
        'لديك ١٥ غرفة لإنهائها ويطلب منك نزيل تنظيف غرفته فوراً. ماذا تفعل؟',
        ['problem_solving', 'customer_focus', 'ownership'],
      ),
      closer,
    ],
  },
  {
    id: 'commis-chef',
    title: 'Commis Chef / Cook',
    titleAr: 'مساعد طاهٍ / طباخ',
    industry: 'Food & Beverage',
    industryAr: 'الأغذية والمشروبات',
    level: 'Entry',
    blurb: 'Kitchen sections, food safety, service pressure and consistency.',
    blurbAr: 'أقسام المطبخ وسلامة الغذاء وضغط الخدمة والاتساق في الجودة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'food_safety',
        'What are your food safety habits, such as temperatures, storage and cross-contamination?',
        'ما عاداتك في سلامة الغذاء، مثل درجات الحرارة والتخزين ومنع التلوث المتبادل؟',
        ['compliance', 'evidence', 'communication'],
        'Be specific with real temperatures and real practices. This is what gets you hired in the Gulf.',
        'كن دقيقاً بدرجات حرارة وممارسات حقيقية. هذا ما يؤهلك للتوظيف في الخليج.',
        20,
        90,
      ),
      q(
        'service_rush',
        'Tell me about the busiest service you have worked. How did you keep up?',
        'حدثني عن أكثر خدمة ازدحاماً عملت فيها. كيف واكبت الضغط؟',
        ['problem_solving', 'ownership', 'evidence'],
      ),
      q(
        'mistake_kitchen',
        'Tell me about a dish you got wrong. What happened next?',
        'حدثني عن طبق أخطأت فيه. ماذا حدث بعد ذلك؟',
        ['ownership', 'compliance', 'communication'],
      ),
      closer,
    ],
  },
  {
    id: 'barista',
    title: 'Barista',
    titleAr: 'باريستا',
    industry: 'Food & Beverage',
    industryAr: 'الأغذية والمشروبات',
    level: 'Entry',
    blurb: 'Coffee craft, speed at peak, regulars and cafe cleanliness.',
    blurbAr: 'إعداد القهوة والسرعة في أوقات الذروة والزبائن الدائمين ونظافة المقهى.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'coffee_craft',
        'How do you make sure every coffee you serve tastes the same as the last one?',
        'كيف تضمن أن كل قهوة تقدّمها بنفس مذاق التي قبلها؟',
        ['evidence', 'communication', 'customer_focus'],
        'Name the real things you check: grind, dose, extraction time, milk texture.',
        'اذكر ما تتحقق منه فعلياً: الطحن والجرعة ووقت الاستخلاص وقوام الحليب.',
        20,
        90,
      ),
      q(
        'morning_rush',
        'There are twelve people in the queue and the machine is struggling. What do you do?',
        'هناك اثنا عشر شخصاً في الطابور والماكينة تتعثر. ماذا تفعل؟',
        ['problem_solving', 'communication', 'customer_focus'],
      ),
      q(
        'remake',
        'A customer says their drink is wrong for the second time today. How do you handle it?',
        'يقول زبون إن مشروبه خاطئ للمرة الثانية اليوم. كيف تتعامل مع ذلك؟',
        ['customer_focus', 'ownership', 'problem_solving'],
      ),
      closer,
    ],
  },
  {
    id: 'fb-supervisor',
    title: 'F&B Supervisor',
    titleAr: 'مشرف أغذية ومشروبات',
    industry: 'Food & Beverage',
    industryAr: 'الأغذية والمشروبات',
    level: 'Mid',
    blurb: 'Shift leadership, covers and targets, staff issues and escalated guests.',
    blurbAr: 'قيادة النوبة وأهداف المبيعات ومشكلات الموظفين والضيوف المُصعّدين.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'escalated_guest',
        'A guest asks for the manager and your waiter has already apologised twice. What do you do?',
        'يطلب ضيف المدير وقد اعتذر النادل مرتين بالفعل. ماذا تفعل؟',
        ['customer_focus', 'ownership', 'problem_solving', 'communication'],
      ),
      q(
        'staff_issue',
        'One of your team keeps arriving late. How do you handle it?',
        'أحد أفراد فريقك يتأخر باستمرار. كيف تتعامل مع ذلك؟',
        ['ownership', 'communication', 'problem_solving'],
      ),
      q(
        'covers_targets',
        'How do you run a shift briefing, and what do you actually cover in it?',
        'كيف تدير اجتماع بداية النوبة، وماذا تغطي فيه فعلياً؟',
        ['communication', 'evidence'],
        'Be concrete: numbers, specials, staffing, and what you ask the team for.',
        'كن محدداً: الأرقام والأطباق المميزة والتوزيع وما تطلبه من الفريق.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'kitchen-steward',
    title: 'Kitchen Steward',
    titleAr: 'ستيوارد مطبخ',
    industry: 'Food & Beverage',
    industryAr: 'الأغذية والمشروبات',
    level: 'Entry',
    blurb: 'Dishwashing and equipment, kitchen hygiene, chemicals and service pressure.',
    blurbAr: 'غسل الأواني والمعدات ونظافة المطبخ والمواد الكيميائية وضغط الخدمة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'steward_hygiene',
        'How do you make sure kitchen equipment is properly clean and safe to use?',
        'كيف تتأكد أن معدات المطبخ نظيفة تماماً وآمنة للاستخدام؟',
        ['compliance', 'evidence', 'communication'],
        'Be specific about your washing, sanitising and drying steps.',
        'كن محدداً بشأن خطوات الغسل والتعقيم والتجفيف لديك.',
        20,
        90,
      ),
      q(
        'steward_pressure',
        'It is the middle of service and clean pans are running out. What do you do?',
        'أنت في منتصف الخدمة وبدأت الأواني النظيفة تنفد. ماذا تفعل؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'steward_chemicals',
        'How do you handle cleaning chemicals safely in a busy kitchen?',
        'كيف تتعامل مع مواد التنظيف الكيميائية بأمان في مطبخ مزدحم؟',
        ['compliance', 'evidence', 'ownership'],
      ),
      closer,
    ],
  },
  {
    id: 'bellman-concierge',
    title: 'Bellman / Concierge',
    titleAr: 'بيلمان / كونسيرج',
    industry: 'Hospitality',
    industryAr: 'الضيافة',
    level: 'Entry',
    blurb: 'Luggage and arrivals, guest requests, directions, bookings and first impressions.',
    blurbAr: 'الأمتعة والوصول وطلبات النزلاء والإرشادات والحجوزات والانطباع الأول.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'impossible_request',
        'A guest asks you for something that seems impossible to arrange. What do you do?',
        'يطلب منك نزيل شيئاً يبدو من المستحيل ترتيبه. ماذا تفعل؟',
        ['customer_focus', 'problem_solving', 'ownership', 'evidence'],
      ),
      q(
        'local_knowledge',
        'A guest asks you where to go tonight. How do you answer?',
        'يسألك نزيل عن مكان يذهب إليه الليلة. كيف تجيب؟',
        ['customer_focus', 'communication', 'evidence'],
        'Show that you ask what they actually want before recommending anything.',
        'أظهر أنك تسأل عمّا يريدونه فعلاً قبل أن ترشّح أي شيء.',
      ),
      q(
        'luggage_problem',
        'A guest says an item is missing from their luggage. What do you do?',
        'يقول نزيل إن غرضاً مفقود من أمتعته. ماذا تفعل؟',
        ['ownership', 'communication', 'problem_solving'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
];

export const aviationRoles: Role[] = [
  {
    id: 'cabin-crew',
    title: 'Cabin Crew',
    titleAr: 'مضيف طيران',
    industry: 'Aviation',
    industryAr: 'الطيران',
    level: 'Entry',
    blurb: 'Airline cabin service, safety duties, difficult passengers and grooming standards.',
    blurbAr: 'خدمة المقصورة ومهام السلامة والركاب الصعبين ومعايير المظهر.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'difficult_passenger',
        'A passenger refuses to follow a safety instruction during boarding. What do you do?',
        'يرفض أحد الركاب اتباع تعليمات السلامة أثناء الصعود. ماذا تفعل؟',
        ['customer_focus', 'ownership', 'communication', 'problem_solving'],
        'Airlines want firmness with warmth. Show both, and say when you involve the purser.',
        'تبحث شركات الطيران عن الحزم مع اللطف. أظهر الاثنين، ووضّح متى تُشرك رئيس الطاقم.',
      ),
      q(
        'teamwork_crew',
        'You are crewed with people you have never met and one of them is not pulling their weight. What do you do?',
        'تعمل مع طاقم لم تقابله من قبل وأحدهم لا يؤدي دوره. ماذا تفعل؟',
        ['ownership', 'communication', 'problem_solving'],
      ),
      q(
        'service_recovery_air',
        'Tell me about a time you turned an unhappy customer into a satisfied one.',
        'حدثني عن مرة حوّلت فيها عميلاً غير راضٍ إلى عميل راضٍ.',
        ['customer_focus', 'evidence', 'ownership'],
      ),
      closer,
    ],
  },
  {
    id: 'airport-ground-staff',
    title: 'Airport Ground Staff',
    titleAr: 'موظف خدمات أرضية',
    industry: 'Aviation',
    industryAr: 'الطيران',
    level: 'Entry',
    blurb: 'Check-in desks, boarding gates, delays and passenger documentation.',
    blurbAr: 'مكاتب تسجيل الوصول وبوابات الصعود والتأخيرات ووثائق المسافرين.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'flight_delay',
        'A flight is delayed four hours and 200 passengers are at your desk. How do you handle it?',
        'تأخرت رحلة أربع ساعات و٢٠٠ مسافر أمام مكتبك. كيف تتعامل مع ذلك؟',
        ['customer_focus', 'communication', 'problem_solving', 'ownership'],
      ),
      q(
        'documents',
        'A passenger does not have the right visa or documents for their destination. What do you do?',
        'ليس لدى مسافر التأشيرة أو الوثائق الصحيحة لوجهته. ماذا تفعل؟',
        ['compliance', 'communication', 'customer_focus'],
        'Rules matter here, but so does how you deliver bad news. Show both.',
        'القواعد مهمة هنا، لكن طريقة إيصال الخبر السيئ مهمة أيضاً. أظهر الاثنين.',
      ),
      q(
        'baggage',
        'Tell me about a time you dealt with a passenger whose baggage was lost or overweight.',
        'حدثني عن مرة تعاملت فيها مع مسافر فُقدت أمتعته أو زاد وزنها.',
        ['customer_focus', 'ownership', 'evidence'],
      ),
      closer,
    ],
  },
];
