import { q, opener, closerTechnical, technicalCompetencies, type Role } from './shared';

const SAFETY_HINT =
  'Safety awareness is what is being scored here. Name the actual checks, permits and rules you follow.';
const SAFETY_HINT_AR =
  'الوعي بالسلامة هو ما يُقيَّم هنا. اذكر الفحوصات والتصاريح والقواعد التي تتبعها فعلياً.';

/**
 * Oil, gas and energy is among the largest employers in Saudi Arabia, the UAE,
 * Qatar, Kuwait and Oman. These roles interview heavily on permits, procedure
 * and the discipline to stop work: not on enthusiasm.
 */
export const energyRoles: Role[] = [
  {
    id: 'process-operator',
    title: 'Process / Plant Operator',
    titleAr: 'مشغل عمليات / مشغل محطة',
    industry: 'Oil, Gas & Energy',
    industryAr: 'النفط والغاز والطاقة',
    level: 'Mid',
    blurb: 'Plant rounds, control room, upsets and shutdowns, permits and handover.',
    blurbAr: 'جولات المحطة وغرفة التحكم والاضطرابات والإيقاف والتصاريح وتسليم النوبة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'plant_upset',
        'Tell me about a plant upset or alarm you responded to?',
        'حدثني عن اضطراب أو إنذار في المحطة تعاملت معه. ماذا فعلت؟',
        ['problem_solving', 'ownership', 'compliance', 'evidence'],
      ),
      q(
        'permit_system',
        'Explain how a permit to work system operates and your part in it?',
        'اشرح كيف يعمل نظام تصاريح العمل وما دورك فيه.',
        ['compliance', 'evidence', 'communication'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      q(
        'shift_handover',
        'What does a proper shift handover look like in your plant?',
        'كيف يبدو التسليم الصحيح للنوبة في محطتك؟',
        ['communication', 'compliance', 'evidence'],
        'Be concrete about the logs, readings and open issues you pass on.',
        'كن محدداً بشأن السجلات والقراءات والمسائل المفتوحة التي تسلّمها.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'instrument-technician',
    title: 'Instrument & Control Technician',
    titleAr: 'فني أجهزة قياس وتحكم',
    industry: 'Oil, Gas & Energy',
    industryAr: 'النفط والغاز والطاقة',
    level: 'Mid',
    blurb: 'Calibration, loop checks, transmitters and control valves, plant shutdowns.',
    blurbAr: 'المعايرة وفحص الحلقات وأجهزة الإرسال وصمامات التحكم وإيقاف المحطة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'calibration',
        'Walk me through how you calibrate a transmitter and prove it is correct?',
        'اشرح لي كيف تعاير جهاز إرسال وتتحقق من صحته.',
        ['evidence', 'problem_solving', 'communication'],
        'Name your instruments and your actual steps. Detail is what separates candidates here.',
        'اذكر أجهزتك وخطواتك الفعلية. التفاصيل هي ما يميّز المرشحين هنا.',
      ),
      q(
        'loop_fault',
        'A control loop is behaving strangely. How do you find out why?',
        'حلقة تحكم تتصرف بشكل غريب. كيف تكتشف السبب؟',
        ['problem_solving', 'evidence', 'ownership'],
      ),
      q(
        'isolation_energy',
        'What is your isolation and lock-out procedure before working on live equipment?',
        'ما إجراءات العزل وقفل الطاقة قبل العمل على معدات مغذّاة؟',
        ['compliance', 'ownership', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'pipefitter',
    title: 'Pipefitter',
    titleAr: 'فني تركيب أنابيب',
    industry: 'Oil, Gas & Energy',
    industryAr: 'النفط والغاز والطاقة',
    level: 'Mid',
    blurb: 'Spool fabrication, isometric drawings, fit-up tolerance and pressure testing.',
    blurbAr: 'تجهيز الوصلات والمخططات الأيزومترية ودقة التركيب واختبار الضغط.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'isometrics',
        'How do you work from an isometric drawing to a finished spool?',
        'كيف تعمل من مخطط أيزومتري حتى الوصلة النهائية؟',
        ['evidence', 'problem_solving', 'communication'],
        'Walk through your real steps: measuring, cutting, fit-up, alignment checks.',
        'اشرح خطواتك الحقيقية: القياس والقص والتركيب وفحوصات المحاذاة.',
      ),
      q(
        'drawing_error',
        'You believe the drawing is wrong. What do you do?',
        'تعتقد أن المخطط خاطئ. ماذا تفعل؟',
        ['ownership', 'communication', 'compliance'],
      ),
      q(
        'pressure_test',
        'What do you check before and during a pressure test?',
        'ماذا تتحقق منه قبل وأثناء اختبار الضغط؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'scaffolder',
    title: 'Scaffolder',
    titleAr: 'فني سقالات',
    industry: 'Oil, Gas & Energy',
    industryAr: 'النفط والغاز والطاقة',
    level: 'Entry',
    blurb: 'Erecting and dismantling scaffold, tags and inspection, working at height.',
    blurbAr: 'تركيب وفك السقالات والبطاقات والتفتيش والعمل على ارتفاع.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'scaffold_build',
        'How do you erect a scaffold safely from the ground up?',
        'اشرح لي كيف تركّب سقالة بأمان من الأرض إلى الأعلى.',
        ['compliance', 'evidence', 'problem_solving'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
      ),
      q(
        'scaffold_tag',
        'What do you do if a scaffold tag is missing or red?',
        'ماذا تعني بطاقة السقالة، وماذا تفعل إذا كانت مفقودة أو حمراء؟',
        ['compliance', 'ownership', 'communication'],
        undefined,
        undefined,
        20,
        90,
      ),
      q(
        'height_incident',
        'Tell me about a time you saw something unsafe while working at height?',
        'حدثني عن مرة رأيت فيها شيئاً غير آمن أثناء العمل على ارتفاع.',
        ['compliance', 'ownership', 'communication'],
      ),
      closerTechnical,
    ],
  },
  {
    id: 'qaqc-inspector',
    title: 'QA / QC Inspector',
    titleAr: 'مفتش جودة',
    industry: 'Oil, Gas & Energy',
    industryAr: 'النفط والغاز والطاقة',
    level: 'Mid',
    blurb: 'Inspection and test plans, weld and coating inspection, NDT and reporting.',
    blurbAr: 'خطط الفحص والاختبار وفحص اللحام والطلاء والفحص غير الإتلافي والتقارير.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'nonconformance',
        'Tell me about a non-conformance you raised?',
        'حدثني عن حالة عدم مطابقة رفعتها. ماذا حدث بعد ذلك؟',
        ['compliance', 'ownership', 'evidence', 'communication'],
      ),
      q(
        'pressure_to_pass',
        'A project manager pressures you to pass work you believe is not acceptable. What do you do?',
        'يضغط عليك مدير المشروع لاعتماد عمل تعتقد أنه غير مقبول. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
        'Independence is the whole job here. Show that you hold the standard and stay professional.',
        'الاستقلالية هي جوهر العمل هنا. أظهر أنك تتمسك بالمعيار وتبقى مهنياً.',
      ),
      q(
        'itp',
        'What standards and inspection documents do you work to?',
        'ما المعايير ومستندات الفحص التي تعمل وفقها؟',
        ['evidence', 'compliance'],
        'Name the real codes and documents: ITPs, method statements, whatever you actually use.',
        'اذكر الأكواد والمستندات الحقيقية: خطط الفحص وبيانات الطريقة وما تستخدمه فعلاً.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
];

export const automotiveRoles: Role[] = [
  {
    id: 'car-mechanic',
    title: 'Car Mechanic / Auto Technician',
    titleAr: 'ميكانيكي سيارات / فني سيارات',
    industry: 'Automotive',
    industryAr: 'السيارات',
    level: 'Mid',
    blurb: 'Diagnostics, servicing, repairs, workshop safety and explaining work to owners.',
    blurbAr: 'التشخيص والصيانة والإصلاح وسلامة الورشة وشرح العمل لأصحاب السيارات.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'diagnose_fault',
        'A customer says the car makes a noise but you cannot reproduce it. What do you do?',
        'يقول عميل إن السيارة تصدر صوتاً لكنك لا تستطيع تكرار المشكلة. ماذا تفعل؟',
        ['problem_solving', 'evidence', 'communication'],
        'Walk through your real diagnostic method, including what you ask the customer.',
        'اشرح طريقة التشخيص الحقيقية لديك، بما في ذلك ما تسأله للعميل.',
      ),
      q(
        'extra_repair',
        'You find a serious problem the customer did not ask you to fix. What do you do?',
        'تكتشف مشكلة خطيرة لم يطلب منك العميل إصلاحها. ماذا تفعل؟',
        ['ownership', 'communication', 'compliance'],
        'Honesty and clear explanation are what is being scored, not upselling.',
        'الأمانة والشرح الواضح هما ما يُقيَّم، وليس البيع الإضافي.',
      ),
      q(
        'workshop_safety',
        'What are your safety habits in the workshop, such as lifts, fluids and hot parts?',
        'ما عاداتك في السلامة داخل الورشة، مثل الرافعات والسوائل والأجزاء الساخنة؟',
        ['compliance', 'evidence'],
        undefined,
        undefined,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'service-advisor',
    title: 'Service Advisor',
    titleAr: 'مستشار خدمة',
    industry: 'Automotive',
    industryAr: 'السيارات',
    level: 'Mid',
    blurb: 'Workshop reception, job cards, quotes, delays and unhappy vehicle owners.',
    blurbAr: 'استقبال الورشة وبطاقات العمل وعروض الأسعار والتأخيرات وأصحاب السيارات المستائين.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'bad_news_cost',
        'The repair will cost far more than the customer expected. How do you tell them?',
        'سيكلف الإصلاح أكثر بكثير مما توقع العميل. كيف تخبره؟',
        ['communication', 'customer_focus', 'ownership'],
      ),
      q(
        'delayed_car',
        'A customer’s car is not ready on the promised day. What do you do?',
        'سيارة العميل ليست جاهزة في اليوم الموعود. ماذا تفعل؟',
        ['ownership', 'communication', 'problem_solving'],
      ),
      q(
        'translate_technical',
        'How do you explain a technical repair to a customer who knows nothing about cars?',
        'كيف تشرح إصلاحاً فنياً لعميل لا يعرف شيئاً عن السيارات؟',
        ['communication', 'evidence'],
        'Give a real example rather than saying you keep it simple.',
        'اذكر مثالاً حقيقياً بدل القول إنك تبسّط الأمور.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
];
