import { q, opener, closer, serviceCompetencies, technicalCompetencies, type Role } from './shared';

export const officeRoles: Role[] = [
  {
    id: 'admin-assistant',
    title: 'Administrative Assistant',
    titleAr: 'مساعد إداري',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Mid',
    blurb: 'Office coordination, scheduling, documents and stakeholder handling.',
    blurbAr: 'تنسيق المكتب وجدولة المواعيد والمستندات والتعامل مع الأطراف المعنية.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'competing_priorities',
        'Two managers give you urgent work at the same time. How do you handle it?',
        'يعطيك مديران عملاً عاجلاً في نفس الوقت. كيف تتعامل مع ذلك؟',
        ['problem_solving', 'communication', 'ownership'],
      ),
      q(
        'mistake',
        'Tell me about a mistake you made at work and what you did about it.',
        'حدثني عن خطأ ارتكبته في العمل وماذا فعلت حياله.',
        ['ownership', 'evidence', 'communication'],
        'Employers respect candidates who own mistakes and fix them. Say what you changed afterwards.',
        'يحترم أصحاب العمل من يعترف بأخطائه ويصلحها. اذكر ما غيّرته بعد ذلك.',
      ),
      q(
        'tools',
        'Which office systems do you use, and what do you actually build or manage in them?',
        'ما الأنظمة المكتبية التي تستخدمها، وماذا تنشئ أو تدير بها فعلياً؟',
        ['evidence', 'communication'],
        'Name the tools and the real tasks: reports, trackers, calendars, filing systems.',
        'اذكر الأدوات والمهام الحقيقية: التقارير والمتابعات والتقويمات وأنظمة الحفظ.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'receptionist',
    title: 'Receptionist',
    titleAr: 'موظف استقبال مكتبي',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Entry',
    blurb: 'Front desk, visitors, phones, appointments and first impressions.',
    blurbAr: 'مكتب الاستقبال والزوار والهاتف والمواعيد والانطباع الأول.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'visitor_no_appointment',
        'A visitor arrives without an appointment and insists on seeing the manager. What do you do?',
        'يصل زائر بدون موعد ويصرّ على مقابلة المدير. ماذا تفعل؟',
        ['customer_focus', 'communication', 'problem_solving'],
      ),
      q(
        'juggling_desk',
        'The phone is ringing, a visitor is waiting and your manager needs something urgently. What do you do?',
        'الهاتف يرن وهناك زائر ينتظر ومديرك يحتاج شيئاً عاجلاً. ماذا تفعل؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'confidentiality',
        'Someone asks you for information about a colleague or a client. How do you respond?',
        'يطلب منك أحدهم معلومات عن زميل أو عميل. كيف ترد؟',
        ['compliance', 'communication', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'customer-service',
    title: 'Customer Service Representative',
    titleAr: 'ممثل خدمة عملاء',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Entry',
    blurb: 'Call and chat support, complaints, targets and system notes.',
    blurbAr: 'دعم المكالمات والمحادثات والشكاوى والأهداف وتسجيل الملاحظات.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'angry_caller',
        'A customer is shouting at you on the phone about a problem that is not your fault. What do you do?',
        'عميل يصرخ عليك عبر الهاتف بسبب مشكلة ليست خطأك. ماذا تفعل؟',
        ['customer_focus', 'ownership', 'communication', 'problem_solving'],
      ),
      q(
        'cannot_help',
        'A customer wants something the policy does not allow. How do you tell them?',
        'يريد عميل شيئاً لا تسمح به السياسة. كيف تخبره؟',
        ['communication', 'compliance', 'customer_focus'],
        'Saying no well is the whole skill here. Show how you keep the customer with you.',
        'إتقان قول "لا" هو المهارة كاملة هنا. أظهر كيف تحافظ على العميل معك.',
      ),
      q(
        'metrics',
        'What targets have you worked to, and how did you perform against them?',
        'ما الأهداف التي عملت وفقها، وكيف كان أداؤك مقارنة بها؟',
        ['evidence', 'ownership'],
        'Give the real numbers: calls handled, resolution rate, satisfaction scores.',
        'اذكر الأرقام الحقيقية: المكالمات المُعالجة ونسبة الحل ودرجات الرضا.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'it-support',
    title: 'IT Support Technician',
    titleAr: 'فني دعم تقني',
    industry: 'Technology',
    industryAr: 'التقنية',
    level: 'Mid',
    blurb: 'Helpdesk tickets, troubleshooting, non-technical users and escalation.',
    blurbAr: 'تذاكر الدعم واستكشاف الأعطال والمستخدمون غير التقنيين والتصعيد.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'explain_simply',
        'How do you explain a technical problem to someone who is not technical at all?',
        'كيف تشرح مشكلة تقنية لشخص غير تقني على الإطلاق؟',
        ['communication', 'customer_focus', 'evidence'],
        'Give a real example of doing it, not a general statement about being patient.',
        'اذكر مثالاً حقيقياً على ذلك، وليس عبارة عامة عن كونك صبوراً.',
      ),
      q(
        'unknown_issue',
        'You get a ticket for a problem you have never seen. Walk me through what you do.',
        'تصلك تذكرة عن مشكلة لم ترها من قبل. اشرح لي ماذا ستفعل.',
        ['problem_solving', 'ownership', 'evidence'],
      ),
      q(
        'urgent_user',
        'A senior manager demands you fix their laptop right now, but you are mid-way through a server issue. What do you do?',
        'يطالبك مدير كبير بإصلاح حاسوبه فوراً، لكنك في منتصف معالجة مشكلة خادم. ماذا تفعل؟',
        ['problem_solving', 'communication', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'accountant',
    title: 'Accountant',
    titleAr: 'محاسب',
    industry: 'Finance',
    industryAr: 'المالية',
    level: 'Mid',
    blurb: 'Ledgers, reconciliations, month-end close and VAT compliance.',
    blurbAr: 'دفاتر الحسابات والتسويات والإقفال الشهري والامتثال لضريبة القيمة المضافة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'discrepancy',
        'Tell me about a discrepancy you found in the accounts. How did you resolve it?',
        'حدثني عن اختلاف وجدته في الحسابات. كيف قمت بحله؟',
        ['problem_solving', 'evidence', 'ownership'],
      ),
      q(
        'month_end',
        'Walk me through your month-end close process.',
        'اشرح لي عملية الإقفال الشهري لديك.',
        ['evidence', 'communication', 'compliance'],
        'Be specific about the sequence, the systems, and the deadlines you work to.',
        'كن محدداً بشأن التسلسل والأنظمة والمواعيد النهائية التي تلتزم بها.',
      ),
      q(
        'vat',
        'What is your experience with VAT filing and compliance in this region?',
        'ما خبرتك في تقديم إقرارات ضريبة القيمة المضافة والامتثال في هذه المنطقة؟',
        ['compliance', 'evidence'],
        'If your experience is from another country, say so and explain what transfers.',
        'إذا كانت خبرتك من دولة أخرى، اذكر ذلك واشرح ما يمكن تطبيقه هنا.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'bank-teller',
    title: 'Bank Teller / Relationship Officer',
    titleAr: 'صراف بنك / مسؤول علاقات',
    industry: 'Finance',
    industryAr: 'المالية',
    level: 'Entry',
    blurb: 'Branch counter, cash handling, customer accounts and product referrals.',
    blurbAr: 'كاونتر الفرع والتعامل النقدي وحسابات العملاء وترشيح المنتجات.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'suspicious_transaction',
        'A customer asks you to do something that does not feel right. What do you do?',
        'يطلب منك عميل القيام بشيء لا يبدو صحيحاً. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
        'Compliance is the core of banking. Show that you follow procedure without accusing anyone.',
        'الامتثال هو جوهر العمل المصرفي. أظهر أنك تتبع الإجراءات دون اتهام أحد.',
      ),
      q(
        'selling_products',
        'Tell me about a time you recommended a product that genuinely suited a customer.',
        'حدثني عن مرة رشّحت فيها منتجاً يناسب العميل فعلاً.',
        ['customer_focus', 'evidence', 'communication'],
      ),
      q(
        'cash_accuracy',
        'How do you keep accuracy with cash and customer accounts under pressure?',
        'كيف تحافظ على الدقة في النقد وحسابات العملاء تحت الضغط؟',
        ['compliance', 'evidence', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'sales-executive',
    title: 'Sales Executive',
    titleAr: 'تنفيذي مبيعات',
    industry: 'Sales',
    industryAr: 'المبيعات',
    level: 'Mid',
    blurb: 'B2B pipeline, targets, negotiation and client relationships.',
    blurbAr: 'مسار مبيعات الشركات والأهداف والتفاوض وعلاقات العملاء.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'lost_deal',
        'Tell me about a deal you lost. Why did you lose it and what did you learn?',
        'حدثني عن صفقة خسرتها. لماذا خسرتها وماذا تعلمت؟',
        ['ownership', 'evidence', 'problem_solving'],
      ),
      q(
        'biggest_win',
        'Walk me through your biggest win, from first contact to signature.',
        'اشرح لي أكبر صفقة حققتها، من أول اتصال حتى التوقيع.',
        ['evidence', 'communication', 'customer_focus'],
        'Give the numbers, the timeline, and what you personally did to move it forward.',
        'اذكر الأرقام والجدول الزمني وما فعلته أنت شخصياً لدفعها للأمام.',
        30,
        150,
      ),
      q(
        'pipeline',
        'How do you build and manage your pipeline week to week?',
        'كيف تبني وتدير مسار مبيعاتك أسبوعاً بعد أسبوع؟',
        ['problem_solving', 'evidence'],
        'Describe your actual routine and the tools you track it in.',
        'صف روتينك الفعلي والأدوات التي تتابع بها.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'real-estate-agent',
    title: 'Real Estate Agent',
    titleAr: 'وكيل عقاري',
    industry: 'Real Estate',
    industryAr: 'العقارات',
    level: 'Mid',
    blurb: 'Listings, viewings, commission-only pressure and closing deals.',
    blurbAr: 'العروض والمعاينات وضغط العمولة فقط وإتمام الصفقات.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'first_deal',
        'Tell me about a property deal you closed. Walk me through how it happened.',
        'حدثني عن صفقة عقارية أتممتها. اشرح لي كيف حدثت.',
        ['evidence', 'customer_focus', 'ownership'],
        'Give real detail: the property, the price, the objections and how you handled them.',
        'اذكر تفاصيل حقيقية: العقار والسعر والاعتراضات وكيف تعاملت معها.',
        30,
        150,
      ),
      q(
        'no_commission',
        'This job is commission-heavy and some months are empty. How do you handle that?',
        'هذه الوظيفة تعتمد على العمولة وبعض الأشهر تكون فارغة. كيف تتعامل مع ذلك؟',
        ['ownership', 'problem_solving', 'communication'],
      ),
      q(
        'unrealistic_client',
        'A client wants a property that does not exist at their budget. What do you tell them?',
        'يريد عميل عقاراً غير موجود ضمن ميزانيته. ماذا تقول له؟',
        ['communication', 'customer_focus', 'evidence'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'hr-officer',
    title: 'HR Officer',
    titleAr: 'موظف موارد بشرية',
    industry: 'Human Resources',
    industryAr: 'الموارد البشرية',
    level: 'Mid',
    blurb: 'Recruitment, onboarding, employee relations and labour law basics.',
    blurbAr: 'التوظيف والتأهيل وعلاقات الموظفين وأساسيات قانون العمل.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'grievance',
        'Tell me about an employee complaint you handled. How did it end?',
        'حدثني عن شكوى موظف تعاملت معها. كيف انتهت؟',
        ['ownership', 'communication', 'problem_solving', 'evidence'],
      ),
      q(
        'hiring_volume',
        'You need to fill 20 roles in six weeks. How do you approach it?',
        'تحتاج إلى شغل ٢٠ وظيفة خلال ستة أسابيع. كيف تتعامل مع الأمر؟',
        ['problem_solving', 'evidence', 'ownership'],
      ),
      q(
        'labour_law',
        'What do you know about labour law and visa processes in this region?',
        'ماذا تعرف عن قانون العمل وإجراءات التأشيرات في هذه المنطقة؟',
        ['evidence', 'communication'],
        'Be honest about what you know and what you would need to learn.',
        'كن صادقاً بشأن ما تعرفه وما تحتاج إلى تعلمه.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'teacher',
    title: 'Teacher',
    titleAr: 'معلم',
    industry: 'Education',
    industryAr: 'التعليم',
    level: 'Mid',
    blurb: 'Classroom practice, differentiation, behaviour and parent communication.',
    blurbAr: 'الممارسة الصفية ومراعاة الفروق الفردية والسلوك والتواصل مع أولياء الأمور.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'struggling_student',
        'Tell me about a student who was falling behind. What did you do about it?',
        'حدثني عن طالب كان متأخراً دراسياً. ماذا فعلت حيال ذلك؟',
        ['problem_solving', 'ownership', 'evidence'],
      ),
      q(
        'parent',
        'A parent disagrees strongly with a grade you gave. How do you handle the conversation?',
        'أحد أولياء الأمور يعترض بشدة على درجة منحتها. كيف تدير هذه المحادثة؟',
        ['communication', 'customer_focus', 'ownership'],
      ),
      q(
        'behaviour',
        'How do you manage a class where behaviour is becoming a problem?',
        'كيف تدير صفاً بدأ السلوك فيه يصبح مشكلة؟',
        ['problem_solving', 'communication'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'teaching-assistant',
    title: 'Teaching Assistant / Nursery Staff',
    titleAr: 'مساعد معلم / موظف حضانة',
    industry: 'Education',
    industryAr: 'التعليم',
    level: 'Entry',
    blurb: 'Supporting the classroom, small groups, child safety and parent handover.',
    blurbAr: 'دعم الصف والمجموعات الصغيرة وسلامة الأطفال والتسليم لأولياء الأمور.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'upset_child',
        'A child is crying and will not settle. What do you do?',
        'طفل يبكي ولا يهدأ. ماذا تفعل؟',
        ['customer_focus', 'problem_solving', 'communication'],
      ),
      q(
        'child_safety_school',
        'What are your responsibilities for keeping children safe during the day?',
        'ما مسؤولياتك في الحفاظ على سلامة الأطفال خلال اليوم؟',
        ['compliance', 'ownership', 'evidence'],
        'Be specific: supervision, headcounts, allergies, handover to parents.',
        'كن محدداً: الإشراف وعدّ الأطفال والحساسية والتسليم لأولياء الأمور.',
        20,
        90,
      ),
      q(
        'supporting_teacher',
        'How do you support a teacher without taking over the class?',
        'كيف تدعم المعلم دون أن تستحوذ على الصف؟',
        ['communication', 'ownership'],
      ),
      closer,
    ],
  },
  {
    id: 'document-controller',
    title: 'Document Controller',
    titleAr: 'مراقب وثائق',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Mid',
    blurb: 'Drawing and document registers, revisions, transmittals and project audits.',
    blurbAr: 'سجلات المخططات والوثائق والمراجعات والإرساليات وتدقيق المشاريع.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'wrong_revision',
        'You discover site has been working from an outdated drawing revision. What do you do?',
        'تكتشف أن الموقع يعمل بنسخة قديمة من المخطط. ماذا تفعل؟',
        ['ownership', 'problem_solving', 'compliance', 'communication'],
        'This is the exact failure a document controller exists to prevent. Show urgency and process.',
        'هذا بالضبط الخلل الذي وُجد مراقب الوثائق لمنعه. أظهر سرعة الاستجابة والإجراء.',
      ),
      q(
        'document_systems',
        'Which document control systems have you used and how do you organise a register?',
        'ما أنظمة مراقبة الوثائق التي استخدمتها وكيف تنظّم السجل؟',
        ['evidence', 'communication'],
        'Name the real systems, such as Aconex, SharePoint or EDMS, and your numbering conventions.',
        'اذكر الأنظمة الحقيقية، مثل أكونيكس أو شيربوينت أو أنظمة إدارة الوثائق، وطريقة الترقيم لديك.',
        20,
        90,
      ),
      q(
        'chasing_people',
        'Engineers are late returning documents you need. How do you handle it?',
        'المهندسون متأخرون في إعادة وثائق تحتاجها. كيف تتعامل مع ذلك؟',
        ['communication', 'ownership', 'problem_solving'],
      ),
      closer,
    ],
  },
  {
    id: 'office-assistant',
    title: 'Office Assistant / Data Entry',
    titleAr: 'مساعد مكتبي / مدخل بيانات',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Entry',
    blurb: 'Data entry accuracy, filing, office errands and supporting the whole team.',
    blurbAr: 'دقة إدخال البيانات والأرشفة والمهام المكتبية ودعم الفريق بالكامل.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'data_accuracy',
        'How do you keep data entry accurate when you are doing hundreds of records?',
        'كيف تحافظ على دقة إدخال البيانات عند التعامل مع مئات السجلات؟',
        ['evidence', 'ownership', 'problem_solving'],
        'Give your real checking habits, not just "I am careful".',
        'اذكر عاداتك الحقيقية في المراجعة، وليس فقط "أنا دقيق".',
      ),
      q(
        'entry_error',
        'You realise you entered wrong information that has already been used. What do you do?',
        'تكتشف أنك أدخلت معلومات خاطئة استُخدمت بالفعل. ماذا تفعل؟',
        ['ownership', 'communication', 'compliance'],
      ),
      q(
        'many_bosses',
        'Several people ask you for help at the same time. How do you decide what to do first?',
        'يطلب منك عدة أشخاص المساعدة في نفس الوقت. كيف تقرر ما تبدأ به؟',
        ['problem_solving', 'communication'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'executive-assistant',
    title: 'Executive Assistant',
    titleAr: 'مساعد تنفيذي',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Senior',
    blurb: 'Executive diaries, travel, confidentiality and gatekeeping at senior level.',
    blurbAr: 'جداول المدراء التنفيذيين والسفر والسرية وتنظيم الوصول للإدارة العليا.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'confidential_info',
        'You handle confidential information daily. Tell me how you protect it.',
        'تتعامل مع معلومات سرية يومياً. أخبرني كيف تحميها.',
        ['compliance', 'ownership', 'evidence'],
      ),
      q(
        'diary_clash',
        'Your executive is double-booked with two people who both matter. What do you do?',
        'مديرك التنفيذي لديه موعدان متعارضان مع شخصين مهمين. ماذا تفعل؟',
        ['problem_solving', 'communication', 'ownership'],
      ),
      q(
        'saying_no',
        'How do you turn people away from your executive without damaging the relationship?',
        'كيف تعتذر للآخرين عن مقابلة مديرك دون الإضرار بالعلاقة؟',
        ['communication', 'customer_focus'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'procurement-officer',
    title: 'Procurement / Purchasing Officer',
    titleAr: 'موظف مشتريات',
    industry: 'Corporate',
    industryAr: 'الشركات',
    level: 'Mid',
    blurb: 'Quotations, supplier negotiation, purchase orders and delivery chasing.',
    blurbAr: 'عروض الأسعار والتفاوض مع الموردين وأوامر الشراء ومتابعة التسليم.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'supplier_late',
        'A supplier is late and the site or store needs the material now. What do you do?',
        'المورّد متأخر والموقع أو المتجر يحتاج المواد الآن. ماذا تفعل؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'best_price',
        'How do you decide between three quotations?',
        'كيف تقرر بين ثلاثة عروض أسعار؟',
        ['evidence', 'problem_solving', 'compliance'],
        'Show that you weigh more than price: quality, lead time, payment terms, reliability.',
        'أظهر أنك توازن أكثر من السعر: الجودة ومدة التوريد وشروط الدفع والموثوقية.',
      ),
      q(
        'supplier_gift',
        'A supplier offers you a personal gift. What do you do?',
        'يعرض عليك مورّد هدية شخصية. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'software-developer',
    title: 'Software Developer',
    titleAr: 'مطوّر برمجيات',
    industry: 'Technology',
    industryAr: 'التقنية',
    level: 'Mid',
    blurb: 'Building features, debugging, code review and working with non-technical teams.',
    blurbAr: 'بناء الميزات وتصحيح الأخطاء ومراجعة الكود والعمل مع فرق غير تقنية.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'hard_bug',
        'Tell me about the hardest bug you have fixed. How did you find it?',
        'حدثني عن أصعب خطأ برمجي أصلحته. كيف وجدته؟',
        ['problem_solving', 'evidence', 'ownership'],
        'Walk through your actual debugging process, not just the outcome.',
        'اشرح عملية التصحيح الفعلية لديك، وليس النتيجة فقط.',
        30,
        150,
      ),
      q(
        'code_review_feedback',
        'Someone rejects your code in review. How do you respond?',
        'يرفض أحدهم الكود الخاص بك في المراجعة. كيف ترد؟',
        ['communication', 'ownership'],
      ),
      q(
        'tech_stack',
        'What have you built, and what were you personally responsible for?',
        'ماذا بنيت، وما الذي كنت مسؤولاً عنه شخصياً؟',
        ['evidence', 'communication'],
        'Name the technologies and be honest about your specific contribution.',
        'اذكر التقنيات وكن صادقاً بشأن مساهمتك المحددة.',
        20,
        90,
      ),
      closer,
    ],
  },
];
