import {
  q,
  opener,
  closer,
  closerTechnical,
  serviceCompetencies,
  technicalCompetencies,
  type Role,
} from './shared';

export const logisticsRoles: Role[] = [
  {
    id: 'driver',
    title: 'Driver / Delivery',
    titleAr: 'سائق / مندوب توصيل',
    industry: 'Logistics',
    industryAr: 'الخدمات اللوجستية',
    level: 'Entry',
    blurb: 'Deliveries, route handling, vehicle care and customer contact.',
    blurbAr: 'التوصيل وإدارة المسارات والعناية بالمركبة والتعامل مع العملاء.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'late_delivery',
        'You are running late on a delivery because of traffic. What do you do?',
        'أنت متأخر عن التوصيل بسبب الازدحام. ماذا تفعل؟',
        ['ownership', 'communication', 'problem_solving'],
      ),
      q(
        'vehicle_issue',
        'Tell me about a time something went wrong with your vehicle or your load.',
        'حدثني عن مرة حدث فيها خطأ في مركبتك أو في حمولتك.',
        ['problem_solving', 'compliance', 'evidence'],
      ),
      q(
        'safety',
        'What checks do you do before you start driving for the day?',
        'ما الفحوصات التي تقوم بها قبل بدء القيادة كل يوم؟',
        ['compliance', 'evidence'],
        'List the actual checks. Safety awareness is what is being scored here.',
        'اذكر الفحوصات الفعلية. الوعي بالسلامة هو ما يُقيَّم هنا.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'delivery-rider',
    title: 'Delivery Rider',
    titleAr: 'سائق دراجة توصيل',
    industry: 'Logistics',
    industryAr: 'الخدمات اللوجستية',
    level: 'Entry',
    blurb: 'App-based delivery, order accuracy, heat and traffic, customer doorstep contact.',
    blurbAr: 'التوصيل عبر التطبيقات ودقة الطلبات والحرارة والازدحام والتعامل عند الباب.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'wrong_address',
        'The address on the order is wrong and the customer is not answering. What do you do?',
        'العنوان في الطلب خاطئ والعميل لا يرد. ماذا تفعل؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'rider_safety',
        'How do you keep yourself safe riding in Gulf traffic and summer heat?',
        'كيف تحافظ على سلامتك أثناء القيادة في ازدحام الخليج وحرّ الصيف؟',
        ['compliance', 'ownership', 'evidence'],
        'Be specific and honest. Employers here are judged on rider safety and they know it.',
        'كن محدداً وصادقاً. أصحاب العمل هنا يُحاسبون على سلامة السائقين ويعلمون ذلك.',
        20,
        90,
      ),
      q(
        'angry_customer_door',
        'A customer is angry at the door because the order is late or cold. What do you say?',
        'عميل غاضب عند الباب لأن الطلب متأخر أو بارد. ماذا تقول؟',
        ['customer_focus', 'communication', 'ownership'],
      ),
      closer,
    ],
  },
  {
    id: 'warehouse-storekeeper',
    title: 'Warehouse / Storekeeper',
    titleAr: 'أمين مستودع',
    industry: 'Logistics',
    industryAr: 'الخدمات اللوجستية',
    level: 'Entry',
    blurb: 'Receiving, stock accuracy, picking, forklifts and inventory counts.',
    blurbAr: 'الاستلام ودقة المخزون والتجهيز والرافعات الشوكية والجرد.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'stock_discrepancy',
        'The system says 50 units but you count 44. What do you do?',
        'النظام يقول ٥٠ وحدة لكنك تعدّ ٤٤. ماذا تفعل؟',
        ['problem_solving', 'ownership', 'compliance', 'evidence'],
      ),
      q(
        'wms_systems',
        'Which stock or warehouse systems have you used, and what did you do in them?',
        'ما أنظمة المخزون أو المستودعات التي استخدمتها، وماذا كنت تفعل بها؟',
        ['evidence', 'communication'],
        'Name the real systems and the daily tasks: receiving, picking, cycle counts.',
        'اذكر الأنظمة الحقيقية والمهام اليومية: الاستلام والتجهيز والجرد الدوري.',
        20,
        90,
      ),
      q(
        'warehouse_safety',
        'What are the safety rules you follow around forklifts and stacked goods?',
        'ما قواعد السلامة التي تتبعها حول الرافعات الشوكية والبضائع المكدسة؟',
        ['compliance', 'evidence', 'ownership'],
      ),
      closerTechnical,
    ],
  },
  {
    id: 'taxi-driver',
    title: 'Taxi / Ride-hailing Driver',
    titleAr: 'سائق أجرة / تطبيقات نقل',
    industry: 'Logistics',
    industryAr: 'الخدمات اللوجستية',
    level: 'Entry',
    blurb: 'Passengers, ratings, long shifts, navigation and difficult fares.',
    blurbAr: 'الركاب والتقييمات والنوبات الطويلة والملاحة والرحلات الصعبة.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'difficult_passenger_taxi',
        'A passenger is rude to you or refuses to wear a seatbelt. What do you do?',
        'راكب يتصرف بوقاحة معك أو يرفض ربط حزام الأمان. ماذا تفعل؟',
        ['customer_focus', 'compliance', 'communication'],
      ),
      q(
        'ratings',
        'How do you keep your passenger rating high?',
        'كيف تحافظ على تقييم عالٍ من الركاب؟',
        ['customer_focus', 'evidence', 'ownership'],
        'Give the real things you do: the car, the greeting, the route, the small courtesies.',
        'اذكر ما تفعله فعلياً: السيارة والترحيب والطريق واللفتات الصغيرة.',
        20,
        90,
      ),
      q(
        'long_hours_safety',
        'How do you stay safe and alert during long driving shifts?',
        'كيف تحافظ على سلامتك ويقظتك خلال نوبات القيادة الطويلة؟',
        ['compliance', 'ownership', 'problem_solving'],
      ),
      closer,
    ],
  },
  {
    id: 'truck-driver',
    title: 'Heavy Truck Driver',
    titleAr: 'سائق شاحنة ثقيلة',
    industry: 'Logistics',
    industryAr: 'الخدمات اللوجستية',
    level: 'Mid',
    blurb: 'Heavy vehicle licence, load securing, long routes, checkpoints and vehicle checks.',
    blurbAr: 'رخصة المركبات الثقيلة وتأمين الحمولة والطرق الطويلة ونقاط التفتيش وفحص المركبة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'load_securing',
        'How do you make sure a load is secure before you move?',
        'كيف تتأكد أن الحمولة مؤمّنة قبل التحرك؟',
        ['compliance', 'evidence', 'ownership'],
        'Name the real checks and equipment you use.',
        'اذكر الفحوصات والمعدات الحقيقية التي تستخدمها.',
      ),
      q(
        'breakdown_route',
        'You break down on a long route far from the depot. What do you do?',
        'تتعطل مركبتك في طريق طويل بعيداً عن المستودع. ماذا تفعل؟',
        ['problem_solving', 'communication', 'ownership'],
      ),
      q(
        'driving_hours',
        'What do you do when you are behind schedule but too tired to drive safely?',
        'ماذا تفعل عندما تكون متأخراً عن الجدول لكنك متعب جداً للقيادة بأمان؟',
        ['compliance', 'ownership', 'communication'],
        'The right answer is that you stop. Show how you communicate it.',
        'الإجابة الصحيحة أن تتوقف. أظهر كيف تُبلغ عن ذلك.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
];

export const retailRoles: Role[] = [
  {
    id: 'retail-sales',
    title: 'Retail Sales Associate',
    titleAr: 'مندوب مبيعات تجزئة',
    industry: 'Retail',
    industryAr: 'التجزئة',
    level: 'Entry',
    blurb: 'Mall retail, targets, customer service and stock handling.',
    blurbAr: 'بيع التجزئة في المراكز التجارية والأهداف وخدمة العملاء وإدارة المخزون.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'difficult_customer',
        'Tell me about a customer who wanted to return an item you could not accept. What happened?',
        'حدثني عن عميل أراد إرجاع منتج لم يكن بإمكانك قبوله. ماذا حدث؟',
        ['customer_focus', 'ownership', 'communication'],
      ),
      q(
        'targets',
        'Tell me about a sales target you were given. Did you hit it, and how?',
        'حدثني عن هدف مبيعات كُلّفت به. هل حققته، وكيف؟',
        ['evidence', 'ownership', 'problem_solving'],
        'Give the real numbers if you can: the target, what you achieved, and what you changed.',
        'اذكر الأرقام الحقيقية إن أمكن: الهدف، وما حققته، وما الذي غيّرته.',
      ),
      q(
        'quiet_floor',
        'The store is quiet and you have hours left in your shift. What do you do?',
        'المتجر هادئ ولديك ساعات متبقية في نوبتك. ماذا تفعل؟',
        ['ownership', 'customer_focus'],
        'Employers are testing initiative here. Be specific about what you would actually do.',
        'يختبر أصحاب العمل روح المبادرة هنا. كن محدداً بشأن ما ستفعله فعلياً.',
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'cashier',
    title: 'Cashier',
    titleAr: 'أمين صندوق',
    industry: 'Retail',
    industryAr: 'التجزئة',
    level: 'Entry',
    blurb: 'Tills, cash accuracy, queues, refunds and end-of-shift reconciliation.',
    blurbAr: 'الصناديق ودقة النقد والطوابير والمرتجعات وتسوية نهاية النوبة.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'till_short',
        'Your till is short at the end of your shift. What do you do?',
        'صندوقك ناقص في نهاية النوبة. ماذا تفعل؟',
        ['ownership', 'compliance', 'problem_solving', 'evidence'],
        'Honesty is the whole answer here. Say exactly who you tell and when.',
        'الأمانة هي الإجابة كاملة هنا. حدّد بالضبط من ستُبلغ ومتى.',
      ),
      q(
        'long_queue',
        'There is a long queue and the customer in front of you is disputing a price. What do you do?',
        'هناك طابور طويل والعميل أمامك يعترض على السعر. ماذا تفعل؟',
        ['customer_focus', 'problem_solving', 'communication'],
      ),
      q(
        'payment_accuracy',
        'How do you keep accuracy up when the store is busy and you are rushing?',
        'كيف تحافظ على الدقة عندما يكون المتجر مزدحماً وأنت مستعجل؟',
        ['evidence', 'ownership', 'compliance'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'store-supervisor',
    title: 'Store Supervisor',
    titleAr: 'مشرف متجر',
    industry: 'Retail',
    industryAr: 'التجزئة',
    level: 'Mid',
    blurb: 'Shift running, staff rotas, store targets, shrinkage and escalated customers.',
    blurbAr: 'إدارة النوبات وجداول الموظفين وأهداف المتجر والفاقد والعملاء المُصعّدين.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'underperformer',
        'One of your sales staff is consistently missing their target. How do you handle it?',
        'أحد موظفي المبيعات لديك لا يحقق هدفه باستمرار. كيف تتعامل مع ذلك؟',
        ['ownership', 'communication', 'problem_solving'],
      ),
      q(
        'shrinkage',
        'You suspect stock is going missing. What do you do?',
        'تشك في أن هناك مخزوناً يُفقد. ماذا تفعل؟',
        ['compliance', 'problem_solving', 'ownership'],
        'Be careful and fair in your answer. Process matters more than accusation.',
        'كن حذراً ومنصفاً في إجابتك. الإجراءات أهم من الاتهام.',
      ),
      q(
        'store_targets',
        'How do you keep a team motivated through a slow month?',
        'كيف تحافظ على حماس الفريق خلال شهر بطيء؟',
        ['communication', 'evidence', 'customer_focus'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'beauty-advisor',
    title: 'Beauty Advisor',
    titleAr: 'مستشار تجميل',
    industry: 'Retail',
    industryAr: 'التجزئة',
    level: 'Entry',
    blurb: 'Cosmetics and fragrance counters, consultations, targets and brand knowledge.',
    blurbAr: 'أقسام مستحضرات التجميل والعطور والاستشارات والأهداف ومعرفة العلامات التجارية.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'consultation_beauty',
        'A customer does not know what she wants. How do you help her choose?',
        'عميلة لا تعرف ماذا تريد. كيف تساعدها على الاختيار؟',
        ['customer_focus', 'communication', 'evidence'],
        'Show that you ask questions before recommending, and that you listen to the answers.',
        'أظهر أنك تسأل قبل أن ترشّح، وأنك تستمع للإجابات.',
      ),
      q(
        'wrong_product',
        'A customer says a product you recommended caused a reaction. What do you do?',
        'تقول عميلة إن منتجاً رشّحته سبب لها تحسساً. ماذا تفعل؟',
        ['ownership', 'customer_focus', 'compliance'],
      ),
      q(
        'beauty_targets',
        'How do you reach your sales target without pushing customers into buying?',
        'كيف تحقق هدف مبيعاتك دون الضغط على العملاء للشراء؟',
        ['evidence', 'customer_focus', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
];

export const facilitiesRoles: Role[] = [
  {
    id: 'security-guard',
    title: 'Security Guard',
    titleAr: 'حارس أمن',
    industry: 'Facilities & Security',
    industryAr: 'المرافق والأمن',
    level: 'Entry',
    blurb: 'Site security, access control, incident reporting and de-escalation.',
    blurbAr: 'أمن الموقع والتحكم في الدخول وكتابة تقارير الحوادث وتهدئة المواقف.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'incident',
        'Tell me about an incident you handled on site. What did you do and what did you report?',
        'حدثني عن حادثة تعاملت معها في الموقع. ماذا فعلت وماذا سجّلت في التقرير؟',
        ['ownership', 'problem_solving', 'compliance', 'evidence'],
      ),
      q(
        'refused_entry',
        'Someone without a valid pass insists on entering and becomes aggressive. What do you do?',
        'شخص بدون تصريح صالح يصرّ على الدخول ويصبح عدوانياً. ماذا تفعل؟',
        ['compliance', 'communication', 'problem_solving'],
        'Show how you stay calm, follow procedure, and when you call for backup.',
        'أظهر كيف تحافظ على هدوئك وتتبع الإجراءات ومتى تطلب الدعم.',
      ),
      q(
        'patrol',
        'What does a proper patrol and handover look like at the end of your shift?',
        'كيف تبدو الدورية الصحيحة وتسليم النوبة في نهاية دوامك؟',
        ['compliance', 'communication', 'evidence'],
        'Be concrete about checks, logs, and what you hand to the next guard.',
        'كن محدداً بشأن الفحوصات والسجلات وما تسلّمه للحارس التالي.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'cleaner',
    title: 'Cleaner / Office Attendant',
    titleAr: 'عامل نظافة / مراسل مكتب',
    industry: 'Facilities & Security',
    industryAr: 'المرافق والأمن',
    level: 'Entry',
    blurb: 'Office and building cleaning, chemicals and safety, working around staff.',
    blurbAr: 'تنظيف المكاتب والمباني والمواد الكيميائية والسلامة والعمل بوجود الموظفين.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'cleaning_method',
        'Walk me through how you clean an office area properly.',
        'اشرح لي كيف تنظّف منطقة مكتبية بشكل صحيح.',
        ['evidence', 'communication', 'customer_focus'],
        'Give your real order of work and what you check at the end.',
        'اذكر ترتيب عملك الحقيقي وما تتحقق منه في النهاية.',
        20,
        90,
      ),
      q(
        'chemicals',
        'How do you handle cleaning chemicals safely?',
        'كيف تتعامل مع مواد التنظيف الكيميائية بأمان؟',
        ['compliance', 'evidence', 'ownership'],
      ),
      q(
        'complaint_cleaning',
        'Someone complains that an area you cleaned is not acceptable. What do you do?',
        'يشتكي أحدهم أن منطقة نظّفتها غير مقبولة. ماذا تفعل؟',
        ['customer_focus', 'ownership', 'communication'],
      ),
      closer,
    ],
  },
  {
    id: 'maintenance-technician',
    title: 'Maintenance Technician',
    titleAr: 'فني صيانة',
    industry: 'Facilities & Security',
    industryAr: 'المرافق والأمن',
    level: 'Mid',
    blurb: 'Building maintenance, work orders, AC and general repairs, tenant contact.',
    blurbAr: 'صيانة المباني وأوامر العمل والتكييف والإصلاحات العامة والتعامل مع السكان.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'ac_fault',
        'A tenant says their AC is not cooling. Walk me through what you check.',
        'يقول ساكن إن التكييف لا يبرّد. اشرح لي ما ستفحصه.',
        ['problem_solving', 'evidence', 'communication'],
        'Give your real diagnostic order. This is the most common call in the Gulf.',
        'اذكر ترتيب التشخيص الحقيقي. هذا أكثر بلاغ شيوعاً في الخليج.',
      ),
      q(
        'priorities_maintenance',
        'You have five open work orders and a burst pipe comes in. How do you decide what to do?',
        'لديك خمسة أوامر عمل مفتوحة ويأتيك بلاغ عن انفجار ماسورة. كيف تقرر ما تفعله؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'beyond_skill',
        'You are sent to a job you do not have the skill or parts for. What do you do?',
        'تُرسَل إلى عمل لا تملك مهارته أو قطع غياره. ماذا تفعل؟',
        ['ownership', 'compliance', 'communication'],
        'Honesty about your limits is a strength here, not a weakness.',
        'الصدق بشأن حدود قدراتك قوة هنا وليس ضعفاً.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'spa-therapist',
    title: 'Salon / Spa Therapist',
    titleAr: 'أخصائي صالون / سبا',
    industry: 'Beauty & Wellness',
    industryAr: 'التجميل والعافية',
    level: 'Entry',
    blurb: 'Treatments, client consultation, hygiene standards and retail of products.',
    blurbAr: 'العلاجات واستشارة العملاء ومعايير النظافة وبيع المنتجات.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'consultation',
        'How do you start a treatment with a client you have never met?',
        'كيف تبدأ جلسة علاج مع عميلة لم تقابليها من قبل؟',
        ['customer_focus', 'communication', 'evidence'],
        'Show how you ask about needs, allergies and expectations before you begin.',
        'أظهري كيف تسألين عن الاحتياجات والحساسية والتوقعات قبل البدء.',
      ),
      q(
        'unhappy_client',
        'A client is unhappy with the result at the end of the treatment. What do you do?',
        'عميلة غير راضية عن النتيجة في نهاية الجلسة. ماذا تفعلين؟',
        ['customer_focus', 'ownership', 'problem_solving'],
      ),
      q(
        'hygiene',
        'What are your hygiene standards between clients?',
        'ما معايير النظافة لديك بين عميلة وأخرى؟',
        ['compliance', 'evidence'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
  {
    id: 'personal-trainer',
    title: 'Personal Trainer / Gym Instructor',
    titleAr: 'مدرب شخصي / مدرب صالة',
    industry: 'Beauty & Wellness',
    industryAr: 'التجميل والعافية',
    level: 'Mid',
    blurb: 'Client programmes, safety and form, motivation and selling packages.',
    blurbAr: 'برامج العملاء والسلامة وصحة الأداء والتحفيز وبيع الاشتراكات.',
    competencies: serviceCompetencies,
    questions: [
      opener,
      q(
        'client_progress',
        'Tell me about a client you helped reach their goal. What did you actually do?',
        'حدثني عن عميل ساعدته على تحقيق هدفه. ماذا فعلت فعلياً؟',
        ['evidence', 'ownership', 'customer_focus'],
        'Give real detail: where they started, the programme, how long it took.',
        'اذكر تفاصيل حقيقية: من أين بدأ والبرنامج والمدة التي استغرقها.',
        30,
        150,
      ),
      q(
        'unsafe_exercise',
        'A client insists on lifting a weight you believe is unsafe for them. What do you do?',
        'يصرّ عميل على رفع وزن تعتقد أنه غير آمن له. ماذا تفعل؟',
        ['compliance', 'communication', 'ownership'],
      ),
      q(
        'losing_motivation',
        'A client stops showing up. What do you do?',
        'يتوقف عميل عن الحضور. ماذا تفعل؟',
        ['customer_focus', 'communication', 'problem_solving'],
        undefined,
        undefined,
        20,
        90,
      ),
      closer,
    ],
  },
];
