import { q, opener, closerTechnical, technicalCompetencies, type Role } from './shared';

const SAFETY_HINT =
  'Safety awareness is what is being scored here. Name the actual checks and rules you follow.';
const SAFETY_HINT_AR =
  'الوعي بالسلامة هو ما يُقيَّم هنا. اذكر الفحوصات والقواعد التي تتبعها فعلياً.';

export const tradesRoles: Role[] = [
  {
    id: 'electrician',
    title: 'Electrician',
    titleAr: 'كهربائي',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Installation, fault finding, isolation procedure and site safety.',
    blurbAr: 'التركيب وكشف الأعطال وإجراءات العزل وسلامة الموقع.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'fault_finding',
        'Walk me through how you find and fix an electrical fault you have not seen before?',
        'اشرح لي كيف تكتشف وتصلح عطلاً كهربائياً لم تره من قبل.',
        ['problem_solving', 'evidence', 'communication'],
        'Give your real diagnostic order, step by step, and the instruments you use.',
        'اذكر ترتيب التشخيص الحقيقي لديك خطوة بخطوة والأجهزة التي تستخدمها.',
      ),
      q(
        'isolation',
        'What is your procedure before you work on a live circuit?',
        'ما إجراءاتك قبل العمل على دائرة كهربائية مغذّاة؟',
        ['compliance', 'evidence', 'ownership'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      q(
        'unsafe_instruction',
        'A supervisor tells you to do a job in a way you believe is unsafe. What do you do?',
        'يطلب منك المشرف تنفيذ عمل بطريقة تعتقد أنها غير آمنة. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
      ),
      closerTechnical,
    ],
  },
  {
    id: 'plumber-mep',
    title: 'Plumber / MEP Technician',
    titleAr: 'سبّاك / فني ميكانيكا وكهرباء',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Pipework, leaks, maintenance calls and working in occupied buildings.',
    blurbAr: 'أعمال الأنابيب والتسريبات وطلبات الصيانة والعمل في مبانٍ مأهولة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'leak_diagnosis',
        'A tenant reports a leak but you cannot see where it is coming from. How do you find it?',
        'يبلّغ ساكن عن تسريب لكنك لا ترى مصدره. كيف تجده؟',
        ['problem_solving', 'evidence', 'communication'],
        'Walk through your steps in order, including what you check first and why.',
        'اشرح خطواتك بالترتيب، بما في ذلك ما تفحصه أولاً ولماذا.',
      ),
      q(
        'occupied_property',
        'You have to work in an occupied villa with the family at home. How do you handle that?',
        'عليك العمل في فيلا مأهولة والعائلة في المنزل. كيف تتعامل مع ذلك؟',
        ['communication', 'customer_focus', 'ownership'],
        'Respect for the household is being scored as much as the technical work.',
        'احترام أهل المنزل يُقيَّم بقدر العمل الفني نفسه.',
      ),
      q(
        'water_safety',
        'What checks do you do before you sign off a job as complete?',
        'ما الفحوصات التي تقوم بها قبل اعتماد العمل كمكتمل؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'welder',
    title: 'Welder / Fabricator',
    titleAr: 'لحّام / حدّاد',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Welding processes, weld quality, PPE and hot-work permits.',
    blurbAr: 'عمليات اللحام وجودة اللحام ومعدات الوقاية وتصاريح الأعمال الساخنة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'welding_processes',
        'Which welding processes and materials have you worked with, and to what standards?',
        'ما عمليات اللحام والمواد التي عملت بها، ووفق أي معايير؟',
        ['evidence', 'communication', 'compliance'],
        'Name the real processes (MIG, TIG, arc), thicknesses and any certificates you hold.',
        'اذكر العمليات الفعلية (ميغ، تيغ، القوس الكهربائي) والسماكات وأي شهادات تحملها.',
        20,
        90,
      ),
      q(
        'weld_rejected',
        'What did you do after your weld was rejected during inspection?',
        'حدثني عن لحام لك رُفض أثناء الفحص. ماذا حدث؟',
        ['ownership', 'problem_solving', 'compliance'],
      ),
      q(
        'hot_work',
        'What do you check before starting hot work on site?',
        'ماذا تتحقق منه قبل بدء الأعمال الساخنة في الموقع؟',
        ['compliance', 'evidence', 'ownership'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'foreman',
    title: 'Foreman / Team Leader',
    titleAr: 'مُلاحظ عمال / قائد فريق',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Senior',
    blurb: 'Leading a crew, daily targets, toolbox talks and multi-language teams.',
    blurbAr: 'قيادة فريق العمل والأهداف اليومية واجتماعات السلامة والفرق متعددة اللغات.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'language_barrier',
        'Your crew speaks several different languages. How do you make sure instructions are understood?',
        'فريقك يتحدث عدة لغات مختلفة. كيف تتأكد من فهم التعليمات؟',
        ['communication', 'compliance', 'problem_solving'],
        'This is daily reality on Gulf sites. Be specific about what you actually do.',
        'هذا واقع يومي في مواقع الخليج. كن محدداً بشأن ما تفعله فعلياً.',
      ),
      q(
        'behind_target',
        'Your crew is behind on the day’s target and the client is watching. What do you do?',
        'فريقك متأخر عن هدف اليوم والعميل يراقب. ماذا تفعل؟',
        ['ownership', 'problem_solving', 'communication'],
      ),
      q(
        'unsafe_worker',
        'You catch a worker not wearing his harness at height. What do you do?',
        'تضبط عاملاً لا يرتدي حزام الأمان على ارتفاع. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'hse-officer',
    title: 'HSE / Safety Officer',
    titleAr: 'مسؤول صحة وسلامة',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Site inspections, risk assessments, incident investigation and toolbox talks.',
    blurbAr: 'تفتيش المواقع وتقييم المخاطر والتحقيق في الحوادث واجتماعات السلامة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'stop_work',
        'Tell me about a time you stopped work on site?',
        'حدثني عن مرة أوقفت فيها العمل في الموقع. ماذا حدث بعد ذلك؟',
        ['compliance', 'ownership', 'communication', 'evidence'],
      ),
      q(
        'incident_investigation',
        'Walk me through how you investigate an incident?',
        'اشرح لي كيف تحقق في حادثة وماذا تُنتج في النهاية.',
        ['problem_solving', 'evidence', 'communication'],
        'Give your real process and the documents involved.',
        'اذكر عمليتك الفعلية والمستندات المستخدمة.',
      ),
      q(
        'heat_stress',
        'How do you manage heat stress risk during a Gulf summer?',
        'كيف تدير مخاطر الإجهاد الحراري خلال صيف الخليج؟',
        ['compliance', 'evidence', 'ownership'],
        'Mention the midday break rules and the practical steps you take on site.',
        'اذكر قواعد الاستراحة الظهيرية والخطوات العملية التي تتخذها في الموقع.',
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'civil-engineer',
    title: 'Civil Engineer',
    titleAr: 'مهندس مدني',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Drawings, site supervision, contractors, quality and progress reporting.',
    blurbAr: 'المخططات والإشراف على الموقع والمقاولون والجودة وتقارير التقدم.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'drawing_conflict',
        'What do you do when drawings conflict with work already built on site?',
        'تجد تعارضاً بين المخططات وما هو منفّذ في الموقع. ماذا تفعل؟',
        ['problem_solving', 'communication', 'ownership', 'evidence'],
      ),
      q(
        'contractor_quality',
        'A subcontractor’s work does not meet specification. How do you handle it?',
        'عمل مقاول الباطن لا يطابق المواصفات. كيف تتعامل مع ذلك؟',
        ['compliance', 'communication', 'ownership'],
      ),
      q(
        'project_detail',
        'Tell me about the largest project you have worked on?',
        'حدثني عن أكبر مشروع عملت فيه وما كانت مسؤوليتك.',
        ['evidence', 'communication'],
        'Give real scale, such as value, duration and team size, and your specific scope.',
        'اذكر الحجم الحقيقي، مثل القيمة والمدة وحجم الفريق، ونطاق عملك تحديداً.',
        30,
        150,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'construction-supervisor',
    title: 'Site Supervisor',
    titleAr: 'مشرف موقع',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Senior',
    blurb: 'Site coordination, crew management, HSE and progress reporting.',
    blurbAr: 'تنسيق الموقع وإدارة الفريق والصحة والسلامة وتقارير التقدم.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'safety_incident',
        'Tell me about a safety issue you identified on site?',
        'حدثني عن مشكلة سلامة اكتشفتها في الموقع. ماذا فعلت؟',
        ['compliance', 'ownership', 'problem_solving', 'evidence'],
      ),
      q(
        'behind_schedule',
        'Your crew is behind schedule and the client is pushing. How do you handle it?',
        'فريقك متأخر عن الجدول الزمني والعميل يضغط. كيف تتعامل مع ذلك؟',
        ['problem_solving', 'communication', 'ownership'],
      ),
      q(
        'crew_conflict',
        'How do you handle conflict between workers on your crew?',
        'كيف تتعامل مع الخلافات بين العمال في فريقك؟',
        ['communication', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'mason-steelfixer',
    title: 'Mason / Steel Fixer',
    titleAr: 'بنّاء / حدّاد تسليح',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Entry',
    blurb: 'Blockwork, plastering, rebar to drawings, levels and finishing quality.',
    blurbAr: 'أعمال البلوك والتلييس وحديد التسليح حسب المخططات والمناسيب وجودة التشطيب.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'work_quality',
        'How do you make sure your work is level, square and to the drawing?',
        'كيف تتأكد أن عملك مستوٍ ومتعامد ومطابق للمخطط؟',
        ['evidence', 'compliance', 'problem_solving'],
        'Name the tools and checks you actually use on site.',
        'اذكر الأدوات والفحوصات التي تستخدمها فعلياً في الموقع.',
      ),
      q(
        'rework',
        'What did you do when your work had to be redone?',
        'حدثني عن عمل لك اضطررت لإعادته. ماذا حدث؟',
        ['ownership', 'problem_solving', 'evidence'],
      ),
      q(
        'site_safety_trade',
        'What safety rules do you follow every day on site?',
        'ما قواعد السلامة التي تتبعها يومياً في الموقع؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'carpenter',
    title: 'Carpenter / Shuttering Carpenter',
    titleAr: 'نجار / نجار شدّات',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Entry',
    blurb: 'Formwork and shuttering, joinery, measurements and working to drawings.',
    blurbAr: 'القوالب والشدّات وأعمال النجارة والقياسات والعمل حسب المخططات.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'formwork',
        'How do you prepare formwork for a concrete pour?',
        'اشرح لي كيف تجهّز الشدّة الخشبية لصب الخرسانة.',
        ['evidence', 'compliance', 'problem_solving'],
        'Give your real steps and what you check before the pour starts.',
        'اذكر خطواتك الحقيقية وما تتحقق منه قبل بدء الصب.',
      ),
      q(
        'measurement_error',
        'You realise you have cut material to the wrong measurement. What do you do?',
        'تكتشف أنك قطعت المواد بقياس خاطئ. ماذا تفعل؟',
        ['ownership', 'problem_solving', 'communication'],
      ),
      q(
        'tool_safety',
        'What are your safety rules with power tools and cutting equipment?',
        'ما قواعد السلامة لديك مع العدد الكهربائية ومعدات القص؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'painter',
    title: 'Painter / Decorator',
    titleAr: 'دهّان',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Entry',
    blurb: 'Surface preparation, finishes, snagging and working in occupied buildings.',
    blurbAr: 'تجهيز الأسطح والتشطيبات ومعالجة الملاحظات والعمل في مبانٍ مأهولة.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'surface_prep',
        'Walk me through how you prepare a wall before painting it?',
        'اشرح لي كيف تجهّز الجدار قبل دهانه.',
        ['evidence', 'compliance', 'communication'],
        'Preparation is what separates a good painter from a fast one. Be specific.',
        'التحضير هو ما يميّز الدهّان الجيد عن السريع. كن محدداً.',
      ),
      q(
        'snagging',
        'The client points out defects in your finish. What do you do?',
        'يشير العميل إلى عيوب في تشطيبك. ماذا تفعل؟',
        ['ownership', 'customer_focus', 'problem_solving'],
      ),
      q(
        'paint_safety',
        'How do you work safely with paints, solvents and ventilation?',
        'كيف تعمل بأمان مع الدهانات والمذيبات والتهوية؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'hvac-technician',
    title: 'HVAC / AC Technician',
    titleAr: 'فني تكييف وتبريد',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Split and central AC, chillers, gas charging, servicing and summer breakdowns.',
    blurbAr: 'المكيفات المنفصلة والمركزية والمبردات وشحن الغاز والصيانة وأعطال الصيف.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'not_cooling',
        'How do you find the cause when a unit is running but not cooling?',
        'وحدة تعمل لكنها لا تبرّد. اشرح لي كيف تجد السبب.',
        ['problem_solving', 'evidence', 'communication'],
        'This is the most common call in the Gulf. Give your real diagnostic order.',
        'هذا أكثر بلاغ شيوعاً في الخليج. اذكر ترتيب التشخيص الحقيقي لديك.',
      ),
      q(
        'summer_load',
        'It is July, you have twelve calls waiting and every one is urgent. How do you work?',
        'نحن في يوليو، لديك اثنا عشر بلاغاً منتظراً وكلها عاجلة. كيف تعمل؟',
        ['problem_solving', 'ownership', 'communication'],
      ),
      q(
        'refrigerant',
        'How do you handle refrigerant safely and correctly?',
        'كيف تتعامل مع غاز التبريد بأمان وبشكل صحيح؟',
        ['compliance', 'evidence'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
  {
    id: 'heavy-equipment-operator',
    title: 'Crane / Heavy Equipment Operator',
    titleAr: 'مشغل رافعة / معدات ثقيلة',
    industry: 'Construction & Trades',
    industryAr: 'الإنشاءات والحرف',
    level: 'Mid',
    blurb: 'Lifting operations, load charts, signals, pre-use checks and exclusion zones.',
    blurbAr: 'عمليات الرفع وجداول الأحمال والإشارات والفحوصات قبل التشغيل ومناطق الحظر.',
    competencies: technicalCompetencies,
    questions: [
      opener,
      q(
        'lift_plan',
        'What do you check before you make a lift?',
        'ماذا تتحقق منه قبل تنفيذ عملية رفع؟',
        ['compliance', 'evidence', 'problem_solving'],
        SAFETY_HINT,
        SAFETY_HINT_AR,
      ),
      q(
        'refuse_lift',
        'You are asked to make a lift you do not think is safe. What do you do?',
        'يُطلب منك تنفيذ رفعة لا تعتقد أنها آمنة. ماذا تفعل؟',
        ['compliance', 'ownership', 'communication'],
        'The right answer is that you stop. Show how you say it professionally.',
        'الإجابة الصحيحة أن توقف العمل. أظهر كيف تقولها بأسلوب مهني.',
      ),
      q(
        'signals',
        'How do you work with a banksman or signaller?',
        'كيف تعمل مع الملقّن أو مُعطي الإشارات، وماذا لو غاب عن نظرك؟',
        ['communication', 'compliance', 'ownership'],
        undefined,
        undefined,
        20,
        90,
      ),
      closerTechnical,
    ],
  },
];
