"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { BRAND } from "@/lib/brand";
import { store } from "@/lib/storage";
import { SECTION_META, type RoadmapReport } from "@/lib/types";
import { CoachDrawer } from "./CoachDrawer";
import {
  CoursesSection,
  DayInLifeSection,
  InterviewSection,
  NetworkingSection,
  NinetySection,
  ProjectsSection,
  ResumeSection,
  RiskSection,
  SalarySection,
  SkillGapSection,
  StepsSection,
  TimelineSection,
} from "./Sections";
import { Feedback } from "./Feedback";

export function ReportView() {
  const router = useRouter();
  const [report, setReport] = useState<RoadmapReport | null>(null);
  const [unlocked, setUnlocked] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const r = store.loadReport();
    if (!r) {
      router.replace("/start");
      return;
    }
    setReport(r);
    setUnlocked(store.isUnlocked());
    setLoading(false);
  }, [router]);

  function unlock() {
    // Demo checkout. Wire a real Stripe Checkout session here and flip this
    // flag only after the webhook confirms payment.
    store.setUnlocked(true);
    setUnlocked(true);
    requestAnimationFrame(() =>
      document.getElementById("courses")?.scrollIntoView({ behavior: "smooth", block: "start" })
    );
  }

  if (loading || !report) {
    return (
      <div className="container-page py-24">
        <div className="mx-auto h-64 max-w-3xl animate-pulseSoft rounded-3xl bg-paper-deep/50" />
      </div>
    );
  }

  const s = report.snapshot;

  return (
    <>
      <main className="container-page pb-24 pt-10">
        {/* ── Snapshot header ───────────────────────────────── */}
        <section id="snapshot" className="scroll-mt-28">
          <div className="relative overflow-hidden rounded-[2rem] bg-ever-night px-7 py-10 text-paper-soft sm:px-12 sm:py-14">
            <div
              className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-signal/20 blur-3xl"
              aria-hidden
            />
            <div className="relative">
              <div className="flex flex-wrap items-center gap-3">
                <span className="rounded-full bg-signal/20 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-signal">
                  Your roadmap
                </span>
                <span className="text-sm text-paper-soft/60">
                  {report.generatedBy === "ai" ? "Generated by Claude" : "Generated locally"}
                </span>
              </div>

              <h1 className="mt-5 font-display text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">
                {s.from} <span className="text-signal">→</span> {s.to}
              </h1>

              <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] lg:items-center">
                <p className="text-lg leading-relaxed text-paper-soft/85">{report.verdict}</p>

                <div className="rounded-2xl bg-paper-soft/[0.07] p-6">
                  <div className="flex items-baseline gap-2">
                    <span className="font-display text-5xl font-semibold text-signal">{report.matchScore}</span>
                    <span className="text-paper-soft/60">/ 100 match</span>
                  </div>
                  <div className="mt-3 h-2 w-full overflow-hidden rounded-full bg-paper-soft/15">
                    <div
                      className="h-full rounded-full bg-signal transition-[width] duration-1000"
                      style={{ width: `${report.matchScore}%` }}
                    />
                  </div>
                  <p className="mt-3 text-sm text-paper-soft/60">
                    Based on your transferable skills, weekly hours, timeline, and the
                    difficulty of this specific transition.
                  </p>
                </div>
              </div>

              <div className="mt-9 grid gap-px overflow-hidden rounded-2xl bg-paper-soft/10 sm:grid-cols-4">
                <Fact label="Timeline" value={`${s.months} months`} />
                <Fact label="Commitment" value={`${s.hoursPerWeek} hrs/week`} />
                <Fact label="Skills that transfer" value={`${s.transferableCount} of ${report.skillGap.length}`} />
                <Fact label="Estimated cost" value={s.estimatedCost} />
              </div>
            </div>
          </div>
        </section>

        {/* ── Section nav ───────────────────────────────────── */}
        <nav className="no-print sticky top-[68px] z-30 -mx-5 mt-8 overflow-x-auto border-y border-ink/[0.07] bg-paper/90 px-5 py-3 backdrop-blur-md sm:-mx-8 sm:px-8">
          <ul className="flex gap-1 whitespace-nowrap">
            {SECTION_META.map((m) => (
              <li key={m.id}>
                <a
                  href={`#${m.id}`}
                  className="inline-block rounded-full px-3.5 py-1.5 text-sm text-ink-soft transition-colors hover:bg-paper-deep hover:text-ink"
                >
                  {m.title}
                  {!m.free && !unlocked && <span className="ml-1.5 text-ink-faint" aria-label="locked">🔒</span>}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        <div className="mt-14 space-y-16">
          <SkillGapSection report={report} />
          <StepsSection report={report} unlocked={unlocked} />
          <TimelineSection report={report} />

          {unlocked ? (
            <>
              <CoursesSection report={report} />
              <ProjectsSection report={report} />
              <ResumeSection report={report} />
              <SalarySection report={report} />
              <NetworkingSection report={report} />
              <InterviewSection report={report} />
              <DayInLifeSection report={report} />
              <RiskSection report={report} />
              <NinetySection report={report} />

              <div className="no-print rounded-3xl border border-ink/[0.07] bg-paper-soft p-8 text-center">
                <h2 className="font-display text-2xl font-semibold text-ink">That&rsquo;s the whole plan.</h2>
                <p className="mx-auto mt-2 max-w-xl text-ink-soft">
                  Save it, print it, and put the month-one actions in your calendar today.
                  The coach button stays available for follow-up questions.
                </p>
                <div className="mt-6 flex flex-wrap justify-center gap-3">
                  <button onClick={() => window.print()} className="btn-primary">
                    Save as PDF
                  </button>
                  <Link href="/start" className="btn-ghost">
                    Plan a different transition
                  </Link>
                </div>
              </div>

              <Feedback />
            </>
          ) : (
            <>
              <Paywall report={report} onUnlock={unlock} />
              <Feedback />
            </>
          )}
        </div>
      </main>

      <CoachDrawer report={report} />
    </>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-ever-night px-5 py-4">
      <p className="text-xs uppercase tracking-wider text-paper-soft/50">{label}</p>
      <p className="mt-1 font-display text-lg font-semibold">{value}</p>
    </div>
  );
}

function Paywall({ report, onUnlock }: { report: RoadmapReport; onUnlock: () => void }) {
  const locked = SECTION_META.filter((m) => !m.free);

  return (
    <div className="no-print">
      {/* Teaser: real first course, blurred */}
      <div className="relative">
        <div className="locked-blur" aria-hidden>
          <CoursesSection report={report} />
        </div>
        <div className="absolute inset-x-0 bottom-0 top-1/3 bg-gradient-to-b from-transparent via-paper/80 to-paper" />
      </div>

      <div className="relative -mt-16">
        <div className="overflow-hidden rounded-[2rem] border border-ink/[0.08] bg-paper-soft shadow-float">
          <div className="border-b border-ink/[0.07] px-8 py-10 text-center sm:px-12">
            <span className="eyebrow">9 sections still locked</span>
            <h2 className="mx-auto mt-4 max-w-xl font-display text-3xl font-semibold leading-tight tracking-tight text-ink text-balance sm:text-4xl">
              You&rsquo;ve seen the diagnosis. The rest is the treatment.
            </h2>
            <p className="mx-auto mt-4 max-w-lg leading-relaxed text-ink-soft">
              Courses filtered to your budget, portfolio projects built on your{" "}
              {report.snapshot.from.toLowerCase()} background, salary stages, the interview
              narrative, an honest risk read, and your first 90 days on the job.
            </p>

            <div className="mx-auto mt-8 max-w-md rounded-2xl bg-paper-deep/60 px-6 py-4">
              <p className="text-[15px] text-ink-soft">
                A career coach charges{" "}
                <strong className="font-semibold text-ink">${BRAND.priceAnchor}+ an hour</strong>{" "}
                and would take two weeks to produce less than this.
              </p>
            </div>

            <button onClick={onUnlock} className="btn-signal mt-8 text-base">
              Unlock the full roadmap — ${BRAND.price}
            </button>
            <p className="mt-3 text-sm text-ink-faint">
              One-time payment. No subscription. {BRAND.guaranteeDays}-day money-back guarantee.
            </p>
            <p className="mt-1 text-xs text-ink-faint/70">
              🔒 Secure checkout. Demo build — unlocking is instant and free.
            </p>
          </div>

          <ul className="grid gap-px bg-ink/[0.06] sm:grid-cols-2 lg:grid-cols-3">
            {locked.map((m) => (
              <li key={m.id} className="bg-paper-soft p-6">
                <div className="flex items-start gap-3">
                  <span className="text-lg" aria-hidden>{m.icon}</span>
                  <div>
                    <h3 className="font-display font-semibold leading-snug text-ink">{m.title}</h3>
                    <p className="mt-1 text-sm leading-relaxed text-ink-faint">{m.blurb}</p>
                  </div>
                </div>
                <div className="mt-4 space-y-2" aria-hidden>
                  {[100, 82, 91, 64].map((w, i) => (
                    <div
                      key={i}
                      className="h-2 rounded-full bg-ink/[0.07]"
                      style={{ width: `${w}%` }}
                    />
                  ))}
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
