import type { Lang } from './i18n';

export type MarketingSection = {
  title: string;
  body: string;
  points?: string[];
  href?: string;
  linkLabel?: string;
};

export type MarketingRole = {
  id: string;
  industry: string;
  industryAr: string;
  title: string;
  titleAr: string;
  blurb: string;
  blurbAr: string;
  questionCount: number;
};

export type MarketingPageContent = {
  eyebrow: string;
  title: string;
  intro: string;
  sections: MarketingSection[];
};

type Localised<T> = Record<Lang, T>;

export const marketingNav: Localised<Record<string, string>> = {
  en: {
    how: 'How it works',
    roles: 'Interview roles',
    feedback: 'Your feedback',
    about: 'About',
    faq: 'FAQ',
    blog: 'Guides',
    hiring: 'Hiring teams',
    candidates: 'For candidates',
    practice: 'Practise one answer, free',
    progress: 'My progress',
    owner: 'by Inspire Ambitions',
  },
  ar: {
    how: 'كيف يعمل',
    roles: 'وظائف المقابلات',
    feedback: 'ملاحظاتك',
    about: 'من نحن',
    faq: 'الأسئلة الشائعة',
    blog: 'الأدلة',
    hiring: 'لفرق التوظيف',
    candidates: 'للمرشحين',
    practice: 'جرّب إجابة واحدة مجاناً',
    progress: 'تقدمي',
    owner: 'من إنسباير أمبيشنز',
  },
};

export const founderLine: Localised<string> = {
  en: 'Built by an HR Career Specialist with 20 years on the hiring side of Gulf hospitality.',
  ar: 'من تصميم أخصائي مسار مهني في الموارد البشرية بخبرة ٢٠ عاماً في جانب التوظيف بقطاع الضيافة الخليجي.',
};

export const homeCopy: Localised<Record<string, string>> = {
  en: {
    eyebrow: 'Private practice for Gulf job interviews',
    title: 'Proof, not performance.',
    intro:
      'Choose your job. Answer in English or Arabic. Muqabala shows what you did well, what is missing and what to add next.',
    primary: 'Practise one answer, free. No account.',
    secondary: 'See an example',
    trust: 'Free. No sign-up. We never score your face, accent or personality.',
    statsRoles: 'Roles covered',
    statsQuestions: 'Questions in the bank',
    statsIndustries: 'Industries',
    questionLabel: 'Practice question',
    question: 'Tell me about a time you handled an unhappy customer.',
    answerLabel: 'Your answer',
    answerBefore: 'A guest was upset because their room was not ready. ',
    answerEvidence: 'I checked the booking, found a quiet waiting area and updated them every ten minutes.',
    answerAfter: ' They thanked me when the room was ready.',
    evidenceLabel: 'What you did well',
    evidenceTitle: 'You said what you did',
    evidenceBody: 'You explained your action. You also said how you kept the guest informed.',
    improveLabel: 'Add this next',
    improveBody: 'Say how fast you solved the problem. Then explain how the guest felt at the end.',
    jobTitle: 'Do you have a job advert?',
    jobBody: 'Paste it here. Muqabala will build a full interview for that job.',
    jobCta: 'Start with your job advert',
    stepsTitle: 'Three simple steps',
    step1Title: '1. Pick a job',
    step1Body: 'Choose a job from the list. You can also paste a job advert.',
    step2Title: '2. Give your answer',
    step2Body: 'Speak or type. Check the words before you ask for feedback.',
    step3Title: '3. Read your feedback',
    step3Body: 'See what worked. See what to add. Then try the question again.',
    actEyebrow: 'What you get',
    actTitle: 'Feedback you can act on',
    act1Title: 'A rubric you can see',
    act1Body: 'Each question shows the skills it is scored on before you answer, such as communication, ownership and specific evidence.',
    act2Title: 'Retry that shows the difference',
    act2Body: 'Answer again. Muqabala shows which evidence you added, what changed and what is still missing.',
    act3Title: 'Progress you can track',
    act3Body: 'Every scored attempt is saved to your progress page, so you can watch your answers get stronger.',
    proofTitle: 'How Muqabala judges your answer',
    methodEyebrow: 'Muqabala method',
    proofBody:
      'Muqabala uses the words in your answer. It does not judge your face, accent or personality.',
    methodCta: 'Try the Front Office question',
    exampleSwitchLabel: 'Choose an example role',
    exampleFrontOffice: 'Front Office Agent',
    exampleNurse: 'Staff Nurse',
    nurseQuestion: 'Tell me about a patient whose condition deteriorated on your shift. What did you do?',
    nurseAnswerBefore: 'A post-operative patient became short of breath at 2am. ',
    nurseAnswerEvidence: 'I checked his vital signs, raised the bed, started oxygen and called the doctor with the readings.',
    nurseAnswerAfter: ' He was stable within twenty minutes and I wrote it up before handover.',
    nurseEvidenceTitle: 'You showed your own actions',
    nurseEvidenceBody: 'You listed what you checked and what you did, in order. You also said who you called and when.',
    nurseImproveBody: 'Give the actual readings you saw. Then say what you told the patient while you waited for the doctor.',
    neverTitle: 'We score your answer. We do not score you.',
    trustEyebrow: 'Candidate trust',
    trustCta: 'Practise in private now',
    never1: 'No facial analysis',
    never2: 'No emotion detection',
    never3: 'No accent scoring',
    never4: 'No personality assumptions',
    never5: 'We do not decide who gets hired',
    never6: 'No employer access to practice recordings',
    privacyTitle: 'Your practice is private',
    privacyBody:
      'You can type instead of speaking. You can also fix the written words before you get feedback.',
    privacyStaysLabel: 'Stays on your device:',
    privacyStaysBody: 'your video. Nothing is uploaded.',
    privacySentLabel: 'Sent to our feedback service:',
    privacySentBody: 'the text of your answer only, after you check it.',
    privacyDetail:
      'Progress is saved for seven days before you verify your email. Reports you keep are private to your account.',
    rolesTitle: 'Practise for the job you want',
    rolesBody: 'Start with a popular Gulf role or browse the full directory.',
    allRoles: 'Browse all interview roles',
    hiringTitle: 'Hiring? Turn a job advert into a 12-minute work sample.',
    hiringBody: 'Candidates answer the same three questions. You review every answer and make the decision.',
    hiringCta: 'See Muqabala for hiring teams',
    finalTitle: 'Your next answer can be stronger.',
    finalBody: 'Practise in private. Read your feedback. Try again when you are ready.',
    finalCta: 'Practise your next answer',
  },
  ar: {
    eyebrow: 'تدريب خاص لمقابلات العمل في الخليج',
    title: 'إجابة تُثبِت، لا تُمثِّل',
    intro:
      'اختر الوظيفة. أجب بالعربية أو الإنجليزية. يوضح لك مقابلة ما فعلته جيداً وما ينقص إجابتك وما تضيفه بعد ذلك.',
    primary: 'جرّب إجابة واحدة مجاناً. من دون حساب.',
    secondary: 'شاهد مثالاً',
    trust: 'مجاني ومن دون حساب. لا نقيّم وجهك أو لهجتك أو شخصيتك.',
    statsRoles: 'وظائف مغطاة',
    statsQuestions: 'أسئلة في البنك',
    statsIndustries: 'قطاعات',
    questionLabel: 'سؤال تدريبي',
    question: 'حدثني عن موقف تعاملت فيه مع عميل غير راضٍ.',
    answerLabel: 'إجابتك',
    answerBefore: 'كان أحد النزلاء منزعجاً لأن غرفته لم تكن جاهزة. ',
    answerEvidence: 'راجعت الحجز ووفرت له مكاناً هادئاً للانتظار وأطلعته على المستجدات كل عشر دقائق.',
    answerAfter: ' شكرني عندما أصبحت الغرفة جاهزة.',
    evidenceLabel: 'ما فعلته جيداً',
    evidenceTitle: 'ذكرت ما فعلته',
    evidenceBody: 'شرحت ما فعلته وكيف أخبرت النزيل بما يحدث.',
    improveLabel: 'أضف هذا بعد ذلك',
    improveBody: 'اذكر سرعة حل المشكلة وكيف شعر النزيل في النهاية.',
    jobTitle: 'هل لديك إعلان وظيفة؟',
    jobBody: 'الصقه هنا. سيبني مقابلة كاملة لهذه الوظيفة.',
    jobCta: 'ابدأ بإعلان الوظيفة',
    stepsTitle: 'ثلاث خطوات سهلة',
    step1Title: '١. اختر وظيفة',
    step1Body: 'اختر وظيفة من القائمة أو الصق إعلان الوظيفة.',
    step2Title: '٢. أعط إجابتك',
    step2Body: 'تحدث أو اكتب. راجع الكلمات قبل طلب الملاحظات.',
    step3Title: '٣. اقرأ ملاحظاتك',
    step3Body: 'شاهد ما نجح وما يجب إضافته. ثم حاول مرة أخرى.',
    actEyebrow: 'ما الذي تحصل عليه',
    actTitle: 'ملاحظات يمكنك العمل بها',
    act1Title: 'معايير تراها بنفسك',
    act1Body: 'يعرض كل سؤال المهارات التي يُقيَّم عليها قبل أن تجيب، مثل التواصل وتحمّل المسؤولية والدليل المحدد.',
    act2Title: 'إعادة تُظهر الفرق',
    act2Body: 'أجب مرة أخرى. نوضح لك الدليل الذي أضفته وما تغيّر وما لا يزال ناقصاً.',
    act3Title: 'تقدّم يمكنك متابعته',
    act3Body: 'تُحفظ كل محاولة مقيَّمة في صفحة تقدمك، لترى إجاباتك تصبح أقوى.',
    proofTitle: 'كيف تُقيَّم إجابتك في «مقابلة»',
    methodEyebrow: 'منهج مقابلة',
    proofBody:
      'نستخدم كلمات إجابتك فقط. لا نحكم على وجهك أو لهجتك أو شخصيتك.',
    methodCta: 'جرّب سؤال موظف الاستقبال',
    exampleSwitchLabel: 'اختر وظيفة للمثال',
    exampleFrontOffice: 'موظف استقبال',
    exampleNurse: 'ممرض / ممرضة',
    nurseQuestion: 'حدثني عن مريض تدهورت حالته أثناء نوبتك. ماذا فعلت؟',
    nurseAnswerBefore: 'أصيب مريض بعد عملية جراحية بضيق في التنفس في الساعة الثانية صباحاً. ',
    nurseAnswerEvidence: 'قست العلامات الحيوية، ورفعت السرير، وبدأت الأكسجين، واتصلت بالطبيب وأبلغته بالقراءات.',
    nurseAnswerAfter: ' استقرت حالته خلال عشرين دقيقة وسجّلت ما حدث قبل التسليم.',
    nurseEvidenceTitle: 'أظهرت ما فعلته أنت',
    nurseEvidenceBody: 'ذكرت ما فحصته وما فعلته بالترتيب. وذكرت أيضاً من اتصلت به ومتى.',
    nurseImproveBody: 'اذكر القراءات الفعلية التي رأيتها. ثم قل ماذا قلت للمريض أثناء انتظار الطبيب.',
    neverTitle: 'نقيّم إجابتك. لا نقيّمك أنت.',
    trustEyebrow: 'ثقة المرشح',
    trustCta: 'تدرّب بخصوصية الآن',
    never1: 'لا تحليل للوجه',
    never2: 'لا كشف للمشاعر',
    never3: 'لا تقييم للهجة',
    never4: 'لا افتراضات عن الشخصية',
    never5: 'لا قرارات توظيف آلية',
    never6: 'لا وصول لصاحب العمل إلى تسجيلات التدريب',
    privacyTitle: 'تدريبك خاص',
    privacyBody:
      'يمكنك الكتابة بدلاً من التحدث. ويمكنك تعديل الكلمات قبل الحصول على الملاحظات.',
    privacyStaysLabel: 'يبقى على جهازك:',
    privacyStaysBody: 'الفيديو. لا يُرفع أي شيء.',
    privacySentLabel: 'يُرسل إلى خدمة الملاحظات:',
    privacySentBody: 'نص إجابتك فقط، بعد أن تراجعه.',
    privacyDetail:
      'يُحفظ تقدمك سبعة أيام قبل تأكيد بريدك. التقارير التي تحتفظ بها خاصة بحسابك.',
    rolesTitle: 'تدرّب للوظيفة التي تريدها',
    rolesBody: 'ابدأ بوظيفة خليجية شائعة أو تصفح الدليل الكامل.',
    allRoles: 'تصفح جميع وظائف المقابلات',
    hiringTitle: 'هل توظّف؟ حوّل إعلان الوظيفة إلى عينة عمل مدتها ١٢ دقيقة.',
    hiringBody: 'يجيب المرشحون عن الأسئلة الثلاثة نفسها. تراجع كل إجابة وتتخذ القرار.',
    hiringCta: 'اعرف «مقابلة» لفرق التوظيف',
    finalTitle: 'يمكن أن تكون إجابتك التالية أقوى.',
    finalBody: 'تدرّب بخصوصية وراجع ما يثبت إجابتك ثم حاول مرة أخرى عندما تكون جاهزاً.',
    finalCta: 'تدرّب على إجابتك التالية',
  },
};

/** Days a submitted work sample is kept before automatic deletion. Mirrors docs/screening-v1.md. */
export const SCREENING_RETENTION_DAYS = 90;

/**
 * Where candidate recordings are stored. Read from the Supabase project's region
 * and set in the environment; the data section only names a region when this is
 * present so the page never states a location we have not confirmed.
 */
export const SCREENING_STORAGE_REGION = process.env.NEXT_PUBLIC_SCREENING_STORAGE_REGION?.trim() || null;

export const employerCopy: Localised<Record<string, string>> = {
  en: {
    eyebrow: 'For hiring teams',
    title: 'See who can do the job.',
    sub: 'Turn any job advert into a three-question, 12-minute work sample. Candidates answer in their own words. You make every decision.',
    primaryCta: 'Create your first link, free',
    secondaryCta: 'See a sample report',
    trustLine: 'No automatic rejection. No accent, face or personality scoring. Ever.',
    howEyebrow: 'How it works',
    howTitle: 'Three steps from job advert to shortlist',
    how1Title: 'Paste the job advert',
    how1Body: 'Muqabala builds three focused questions for that role.',
    how2Title: 'Send one secure link',
    how2Body: 'Candidates answer on any device in 12 minutes.',
    how3Title: 'Review every answer and report',
    how3Body: 'You watch the evidence and record the decision.',
    reportEyebrow: 'Sample report',
    reportTitle: 'What you see after a candidate submits',
    reportCaption: 'What you see after a candidate submits.',
    reportBody: 'Recorded answers sit apart from AI notes. Every note quotes the candidate and is marked as unverified until you check it against the video.',
    candidateEyebrow: 'What the candidate sees',
    candidateTitle: 'A calm, timed screen with no surprises',
    candidate1: 'Device check, then a clear consent screen before anything is submitted.',
    candidate2: 'Three timed answers, two minutes each, in the candidate\u2019s own words.',
    fairEyebrow: 'Fair by design',
    fairTitle: 'We score the answer. We never score the person.',
    fair1: 'Never scores accent, nationality, appearance, age, gender presentation or emotion.',
    fair2: 'A human reviews every answer and records every decision.',
    fair3: 'No automatic rejection.',
    fair4: 'Bilingual: English and Arabic question packs.',
    dataEyebrow: 'Data and consent',
    dataTitle: 'Where candidate data lives, and for how long',
    dataStorage: 'Recordings are stored in a private, access-controlled bucket. Only the signed-in employer who created the link can open them.',
    dataRegion: 'Storage region: {region}.',
    dataRetention: 'Submitted interviews are deleted automatically after {days} days. You can delete any interview sooner.',
    dataConsent: 'Candidates see what is recorded and who can open it before question one. Consent is recorded before anything is submitted to you.',
    dataPdpl: 'Consent, purpose limitation and automatic deletion are designed to align with the UAE Personal Data Protection Law.',
    dataGdpr: 'Candidates can ask you to delete their interview at any time, in line with GDPR data subject rights.',
    dataLink: 'Read the privacy page',
    pricingEyebrow: 'Pricing',
    pricingTitle: 'Free to start',
    pricingBody: 'Create links and review answers at no cost. We will show any paid plan clearly before it applies to you.',
    createEyebrow: 'Get started',
    createTitle: 'Create private interview links',
    createBody: 'Sign in with your work email. Only your signed-in account can open the videos and reports.',
    footerCandidates: 'For candidates',
    footerPrivacy: 'Privacy',
    footerTerms: 'Terms',
    footerContact: 'Contact',
    footerLine: 'Work samples for Gulf hiring teams.',
    volumeTitle: '223 applications. Seven worth your time. 48 hours.',
    volumeSub: 'Paste the advert. Paste the emails. Every candidate answers three questions in their own words. You read only the ones who can do the job.',
    volumePrimary: 'Start a shortlist, free',
    volumeSecondary: 'See a real report',
    volumeTrust: 'No automatic rejection. No accent, face or personality scoring. You decide.',
    volumeSampleTitle: 'What you get after a candidate answers',
  },
  ar: {
    eyebrow: 'لفرق التوظيف',
    title: 'اعرف من يستطيع أداء الوظيفة.',
    sub: 'حوّل أي إعلان وظيفة إلى عينة عمل من ثلاثة أسئلة مدتها ١٢ دقيقة. يجيب المرشحون بكلماتهم. وأنت تتخذ كل قرار.',
    primaryCta: 'أنشئ رابطك الأول مجاناً',
    secondaryCta: 'شاهد نموذج تقرير',
    trustLine: 'لا رفض تلقائي. لا تقييم للهجة أو الوجه أو الشخصية. أبداً.',
    howEyebrow: 'كيف يعمل',
    howTitle: 'ثلاث خطوات من إعلان الوظيفة إلى القائمة المختصرة',
    how1Title: 'الصق إعلان الوظيفة',
    how1Body: 'نبني ثلاثة أسئلة مركّزة لهذه الوظيفة.',
    how2Title: 'أرسل رابطاً آمناً واحداً',
    how2Body: 'يجيب المرشحون من أي جهاز خلال ١٢ دقيقة.',
    how3Title: 'راجع كل إجابة وتقرير',
    how3Body: 'تشاهد الدليل وتسجّل القرار.',
    reportEyebrow: 'نموذج تقرير',
    reportTitle: 'ما تراه بعد أن يرسل المرشح إجاباته',
    reportCaption: 'ما تراه بعد أن يرسل المرشح إجاباته.',
    reportBody: 'الإجابات المسجلة منفصلة عن ملاحظات الذكاء الاصطناعي. كل ملاحظة تقتبس كلام المرشح وتُعلَّم بأنها غير مؤكدة حتى تراجعها مع الفيديو.',
    candidateEyebrow: 'ما يراه المرشح',
    candidateTitle: 'شاشة هادئة بوقت محدد ومن دون مفاجآت',
    candidate1: 'فحص الجهاز، ثم شاشة موافقة واضحة قبل إرسال أي شيء.',
    candidate2: 'ثلاث إجابات بوقت محدد، دقيقتان لكل إجابة، بكلمات المرشح.',
    fairEyebrow: 'عادل بالتصميم',
    fairTitle: 'نقيّم الإجابة. لا نقيّم الشخص أبداً.',
    fair1: 'لا تقييم للهجة أو الجنسية أو المظهر أو العمر أو التعبير عن الجنس أو المشاعر.',
    fair2: 'يراجع شخص كل إجابة ويسجّل كل قرار.',
    fair3: 'لا رفض تلقائي.',
    fair4: 'ثنائي اللغة: حزم أسئلة بالإنجليزية والعربية.',
    dataEyebrow: 'البيانات والموافقة',
    dataTitle: 'أين تُحفظ بيانات المرشح، ولأي مدة',
    dataStorage: 'تُحفظ التسجيلات في مخزن خاص محدود الوصول. لا يفتحها إلا صاحب العمل المسجّل الذي أنشأ الرابط.',
    dataRegion: 'منطقة التخزين: {region}.',
    dataRetention: 'تُحذف المقابلات المرسلة تلقائياً بعد {days} يوماً. يمكنك حذف أي مقابلة قبل ذلك.',
    dataConsent: 'يرى المرشح ما يُسجَّل ومن يستطيع فتحه قبل السؤال الأول. وتُسجَّل الموافقة قبل إرسال أي شيء إليك.',
    dataPdpl: 'صُممت الموافقة وتحديد الغرض والحذف التلقائي لتتوافق مع قانون حماية البيانات الشخصية في الإمارات.',
    dataGdpr: 'يمكن للمرشح أن يطلب منك حذف مقابلته في أي وقت، بما يتوافق مع حقوق أصحاب البيانات في اللائحة الأوروبية لحماية البيانات.',
    dataLink: 'اقرأ صفحة الخصوصية',
    pricingEyebrow: 'الأسعار',
    pricingTitle: 'ابدأ مجاناً',
    pricingBody: 'أنشئ الروابط وراجع الإجابات من دون تكلفة. سنعرض أي خطة مدفوعة بوضوح قبل أن تنطبق عليك.',
    createEyebrow: 'ابدأ',
    createTitle: 'أنشئ روابط مقابلة خاصة',
    createBody: 'سجّل الدخول ببريد عملك. حسابك المسجّل فقط يستطيع فتح الفيديوهات والتقارير.',
    footerCandidates: 'للمرشحين',
    footerPrivacy: 'الخصوصية',
    footerTerms: 'الشروط',
    footerContact: 'تواصل',
    footerLine: 'عينات عمل لفرق التوظيف في الخليج.',
    volumeTitle: '٢٢٣ طلباً. سبعة يستحقون وقتك. ٤٨ ساعة.',
    volumeSub: 'الصق الإعلان. الصق عناوين البريد. يجيب كل مرشح عن ثلاثة أسئلة بكلماته. وأنت تقرأ فقط من يستطيع أداء الوظيفة.',
    volumePrimary: 'ابدأ قائمة مختصرة مجاناً',
    volumeSecondary: 'شاهد تقريراً حقيقياً',
    volumeTrust: 'لا رفض تلقائي. لا تقييم للهجة أو الوجه أو الشخصية. أنت تقرر.',
    volumeSampleTitle: 'ما تحصل عليه بعد أن يجيب المرشح',
  },
};

export const infoPages: Record<string, Localised<MarketingPageContent>> = {
  'how-it-works': {
    en: {
      eyebrow: 'How it works',
      title: 'Practise in five easy steps.',
      intro: 'This is private practice. Take your time. No employer can see your answers.',
      sections: [
        { title: '1. Choose a job', body: 'Pick a job from the list. You can also type a job title or paste a job advert.' },
        { title: '2. Speak or type', body: 'Use your camera for real practice. You can also type. Both choices give you the same feedback.' },
        { title: '3. Check the words', body: 'If you spoke, read the written words. Fix any mistake before you ask for feedback.' },
        { title: '4. Read your feedback', body: 'See what you did well. Then see one clear way to make your answer better.' },
        { title: '5. Try again', body: 'Repeat the question as many times as you need. We autosave your progress. Verify your email to continue on another device.' },
      ],
    },
    ar: {
      eyebrow: 'كيف يعمل',
      title: 'تدرّب في خمس خطوات سهلة.',
      intro: 'هذا تدريب خاص. خذ وقتك. لا يرى صاحب العمل إجاباتك.',
      sections: [
        { title: '١. اختر وظيفة', body: 'اختر وظيفة من القائمة. يمكنك أيضاً كتابة المسمى أو لصق إعلان الوظيفة.' },
        { title: '٢. تحدث أو اكتب', body: 'استخدم الكاميرا للتدريب الواقعي أو اكتب. ستحصل على نفس الملاحظات.' },
        { title: '٣. راجع الكلمات', body: 'إذا تحدثت، اقرأ النص وصحح أي خطأ قبل طلب الملاحظات.' },
        { title: '٤. اقرأ ملاحظاتك', body: 'شاهد ما فعلته جيداً وطريقة واحدة واضحة لتحسين إجابتك.' },
        { title: '٥. حاول مرة أخرى', body: 'أعد السؤال بقدر ما تحتاج. يبقى تقدمك في هذا المتصفح.' },
      ],
    },
  },
  'how-feedback-works': {
    en: {
      eyebrow: 'Your feedback',
      title: 'We show why you got your score.',
      intro: 'Muqabala reads the words in your answer. It shows what worked and what you can add next.',
      sections: [
        { title: 'What we look for', body: 'We look for a real example. We check what you did, why you did it and what happened at the end.' },
        { title: 'What we never score', body: 'We do not score your face, looks, eye contact, feelings, accent, grammar or personality.' },
        { title: 'We show the proof', body: 'Your feedback points to words from your answer. If something is missing, we tell you. We do not make it up.' },
        { title: 'Sometimes there is no score', body: 'We may not score an answer if the words are too short or unclear. This helps protect you from a wrong score.' },
        { title: 'Check the feedback', body: 'AI can make mistakes. Read the feedback and decide what is useful. Muqabala does not make hiring decisions.' },
      ],
    },
    ar: {
      eyebrow: 'ملاحظاتك',
      title: 'نوضح سبب درجتك.',
      intro: 'يقرأ مقابلة كلمات إجابتك. يوضح ما نجح وما يمكنك إضافته بعد ذلك.',
      sections: [
        { title: 'ما الذي نبحث عنه', body: 'نبحث عن مثال حقيقي وما فعلته ولماذا فعلته وما حدث في النهاية.' },
        { title: 'ما الذي لا نقيّمه', body: 'لا نقيّم وجهك أو مظهرك أو نظرك أو مشاعرك أو لهجتك أو قواعد اللغة أو شخصيتك.' },
        { title: 'نوضح ما يثبت إجابتك', body: 'تشير الملاحظات إلى كلمات من إجابتك. إذا كان شيء ناقصاً، نخبرك ولا نخترعه.' },
        { title: 'أحياناً لا توجد درجة', body: 'قد لا نقيّم الإجابة إذا كانت قصيرة أو غير واضحة. هذا يحميك من درجة خاطئة.' },
        { title: 'راجع الملاحظات', body: 'قد يخطئ الذكاء الاصطناعي. اقرأ الملاحظات واستخدم حكمك. لا يتخذ مقابلة قرار التوظيف.' },
      ],
    },
  },
  about: {
    en: {
      eyebrow: 'Built for candidates',
      title: 'Interview practice should help, not scare you.',
      intro: 'Muqabala helps people prepare for jobs in the Gulf. You can use it from any country.',
      sections: [
        { title: 'Why we built it', body: 'Many good workers find interviews hard. Private practice helps you explain your real experience clearly.' },
        { title: 'Made for Gulf jobs', body: 'The practice covers jobs in the UAE, Saudi Arabia, Qatar, Oman, Bahrain and Kuwait.' },
        { title: 'People still make hiring decisions', body: 'Muqabala only helps you practise. It does not choose who gets hired. It cannot promise you a job.' },
        { title: 'Built with HR experience', body: 'An HR Career Specialist with more than 20 years of Gulf and African experience leads this project through Inspire Ambitions.' },
      ],
    },
    ar: {
      eyebrow: 'مصمم للمرشحين',
      title: 'يجب أن يبني تدريب المقابلات الثقة، لا الخوف.',
      intro: 'مقابلة مشروع من إنسباير أمبيشنز للأشخاص المتقدمين لوظائف خليجية من المنطقة ومن أنحاء العالم.',
      sections: [
        { title: 'لماذا وُجد مقابلة', body: 'قد يجد المرشح الجيد صعوبة في شرح خبرته تحت الضغط. يساعد التدريب الخاص والمتكرر على تحويل العمل الحقيقي إلى إجابة واضحة تثبت خبرته.' },
        { title: 'خبرة الخليج في المركز', body: 'يعكس المنتج الوظائف وظروف العمل والتوقعات في الإمارات والسعودية وقطر وعمان والبحرين والكويت.' },
        { title: 'الحكم البشري مهم', body: 'يدعم مقابلة الاستعداد ولا يقرر من يجب توظيفه ولا يضمن عرض عمل.' },
        { title: 'موجّه بخبرة الموارد البشرية', body: 'يقود المشروع عبر إنسباير أمبيشنز أخصائي مسار مهني في الموارد البشرية بخبرة تتجاوز 20 عاماً في الخليج وأفريقيا.' },
      ],
    },
  },
  privacy: {
    en: {
      eyebrow: 'Privacy in plain language',
      title: 'Know what happens to your information.',
      intro: 'We explain this before you start. You can type if you do not want to use your camera or microphone.',
      sections: [
        { title: 'Video', body: 'Your video is used for your own practice preview. It is never uploaded or saved by Muqabala.' },
        { title: 'Your voice', body: 'Your browser or our transcription service may process a temporary audio copy to turn it into text. Muqabala does not keep that audio. Choose typing if you do not want this.' },
        { title: 'Your written answer', body: 'We send your written answer to our AI service for feedback. If you paste a job advert, we send its text and job title to make your questions.' },
        { title: 'Your practice history', body: 'We autosave unfinished progress. Before email verification, temporary records expire after seven days. After verification, reports you choose to keep stay private in your account until you delete them.' },
        { title: 'Adaptive text interviews', body: 'Universal Interview Brain V2 stores answers and evidence in encrypted form for 12 months, then deletes them automatically. Account links are held separately. You can delete the interview immediately from its feedback page. We do not use practice data for training without your explicit permission.' },
        { title: 'Report sharing', body: 'A WhatsApp share creates a private link that expires after seven days. The link can be revoked. Anyone who has an active link can read that report.' },
        { title: 'Basic website data', body: 'We use Google Analytics and may use privacy-limited PostHog to understand page use and technical errors. We do not send your name, email, video, voice, answers or job advert. Private link identifiers are replaced with generic route labels.' },
      ],
    },
    ar: {
      eyebrow: 'الخصوصية بلغة واضحة',
      title: 'اعرف ما يبقى وما يتم إرساله.',
      intro: 'يشرح مقابلة استخدام البيانات قبل بدء التدريب ويمكنك الكتابة بدلاً من استخدام الكاميرا أو الميكروفون.',
      sections: [
        { title: 'الفيديو', body: 'يُستخدم الفيديو لمعاينة تدريبك فقط ولا يرفعه مقابلة أو يحفظه.' },
        { title: 'الصوت والتعرف على الكلام', body: 'عندما لا يكون التعرف على الكلام مؤكداً داخل الجهاز، قد يرسل المتصفح الصوت إلى خدمة الكلام الخاصة به. استخدم الكتابة إذا كنت لا تريد ذلك.' },
        { title: 'النص وإعلان الوظيفة', body: 'يُرسل نص إجابتك إلى مسار التقييم ثم إلى مزود الذكاء الاصطناعي. يُرسل إعلان الوظيفة والمسمى لإنشاء أسئلة مخصصة.' },
        { title: 'سجل التدريب', body: 'نحفظ التقدم غير المكتمل تلقائياً. تنتهي السجلات المؤقتة بعد سبعة أيام قبل تأكيد البريد. بعد التأكيد، تبقى التقارير التي تختارها خاصة في حسابك حتى تحذفها.' },
        { title: 'المقابلات النصية المتكيفة', body: 'يخزن محرك المقابلات الشامل V2 الإجابات والأدلة بصورة مشفرة لمدة 12 شهراً ثم يحذفها تلقائياً. تُحفظ روابط الحساب في جدول منفصل. يمكنك حذف المقابلة فوراً من صفحة الملاحظات. لا نستخدم بيانات التدريب للتدريب من دون إذنك الصريح.' },
        { title: 'مشاركة التقرير', body: 'تنشئ المشاركة عبر واتساب رابطاً خاصاً ينتهي بعد سبعة أيام ويمكن إلغاؤه. أي شخص لديه رابط نشط يمكنه قراءة التقرير.' },
        { title: 'التحليلات والأخطاء التقنية', body: 'يستخدم مقابلة Google Analytics وقد يستخدم PostHog بإعدادات محدودة لفهم استخدام الصفحات والأخطاء التقنية. لا نرسل اسمك أو بريدك الإلكتروني أو الفيديو أو الصوت أو الإجابات أو إعلان الوظيفة. نستبدل رموز الروابط الخاصة بتسميات عامة للمسارات.' },
      ],
    },
  },
  terms: {
    en: {
      eyebrow: 'Terms of use',
      title: 'Muqabala is for practice only.',
      intro: 'Use the feedback to help you prepare. Check it and decide what is useful.',
      sections: [
        { title: 'Practice only', body: 'Muqabala is not an employer or recruitment agency. It cannot promise an interview or a job.' },
        { title: 'AI can be wrong', body: 'Questions, written words, feedback and scores can have mistakes. Check them before you act.' },
        { title: 'Protect private information', body: 'Only share information you have the right to use. Do not add private details about an employer, client or person.' },
        { title: 'Use the service fairly', body: 'Do not attack, break or misuse the service. Do not use it to make automatic hiring decisions.' },
        { title: 'The service may change', body: 'We may improve or change features. The service may sometimes stop working for a short time.' },
      ],
    },
    ar: {
      eyebrow: 'شروط الاستخدام',
      title: 'إرشاد للتدريب، وليس قرار توظيف.',
      intro: 'باستخدام مقابلة، توافق على استخدامه للاستعداد للمقابلات وعلى تطبيق حكمك على ملاحظاته.',
      sections: [
        { title: 'للتدريب فقط', body: 'لا يمثل مقابلة صاحب عمل أو وكالة توظيف أو عرض عمل ولا يضمن مقابلة أو وظيفة أو نتيجة محددة.' },
        { title: 'حدود الذكاء الاصطناعي', body: 'قد تحتوي الأسئلة والنصوص والملاحظات والدرجات على أخطاء. راجع النص وما يثبت إجابتك قبل الاعتماد على أي اقتراح.' },
        { title: 'محتواك', body: 'أرسل فقط إعلانات الوظائف والمحتوى الذي يحق لك استخدامه ولا تدرج معلومات سرية عن صاحب عمل أو عميل أو شخص.' },
        { title: 'الاستخدام المقبول', body: 'لا تسئ استخدام الخدمة أو تحاول تعطيلها أو هندسة الأنظمة المحمية عكسياً أو استخدامها لاتخاذ قرارات توظيف آلية.' },
        { title: 'التغييرات والتوفر', body: 'قد تتغير الميزات أثناء التطوير وقد تحدث انقطاعات مؤقتة. قد يؤدي تعطل خدمة التقييم إلى ترك الإجابة دون درجة.' },
      ],
    },
  },
  faq: {
    en: {
      eyebrow: 'Questions before you practise',
      title: 'Your questions, answered.',
      intro: 'Read these short answers before you start.',
      sections: [
        { title: 'Is Muqabala free?', body: 'Yes. Practice is free and unlimited now. We will clearly show any paid choice before you use it.' },
        { title: 'Will an employer see my recording?', body: 'No. Muqabala Coach is private candidate practice. Your video is not uploaded and there is no employer access to your practice history.' },
        { title: 'Does it score my face or accent?', body: 'No. The scoring policy excludes face, appearance, eye contact, emotion, accent, pronunciation, grammar fluency and personality.' },
        { title: 'Can I practise in Arabic?', body: 'Yes. The website and questions work in Arabic and English. If we cannot score an Arabic answer fairly, we will not give a score.' },
        { title: 'Do I need a camera?', body: 'No. You can type and receive the same content feedback. A camera can make practice feel more realistic, but it is not scored.' },
        { title: 'What if the written words are wrong?', body: 'Fix them before you ask for feedback. If the words are too unclear, Muqabala will not give a score.' },
      ],
    },
    ar: {
      eyebrow: 'أسئلة قبل التدريب',
      title: 'إجابات واضحة قبل تشغيل الكاميرا.',
      intro: 'يجب أن تعرف كيف يعمل مقابلة وما تكلفته وما يحدث لتدريبك قبل أن تبدأ.',
      sections: [
        { title: 'هل مقابلة مجاني؟', body: 'تجربة التدريب الحالية مجانية وغير محدودة. سيظهر أي خيار مدفوع مستقبلي بوضوح قبل أن يؤثر على الوصول.' },
        { title: 'هل يرى صاحب العمل تسجيلي؟', body: 'لا. مقابلة كوتش تدريب خاص للمرشح ولا يرفع الفيديو ولا يمنح صاحب العمل وصولاً إلى سجل التدريب.' },
        { title: 'هل يقيّم وجهي أو لهجتي؟', body: 'لا. تستبعد سياسة التقييم الوجه والمظهر والتواصل البصري والمشاعر واللهجة والنطق والطلاقة النحوية والشخصية.' },
        { title: 'هل يمكنني التدريب بالعربية؟', body: 'نعم عندما يتوفر تقييم الذكاء الاصطناعي. تدعم الواجهة والأسئلة العربية والإنجليزية. إذا لم يستطع مسار التقييم تقييم العربية بعدل، يرفض بدلاً من اختراع درجة.' },
        { title: 'هل أحتاج إلى كاميرا؟', body: 'لا. يمكنك الكتابة والحصول على نفس ملاحظات المحتوى. تجعل الكاميرا التدريب أكثر واقعية لكنها ليست جزءاً من التقييم.' },
        { title: 'ماذا لو كان النص خاطئاً؟', body: 'عدّله قبل التقييم. إذا كان النص غير موثوق بدرجة تمنع التقييم، يترك مقابلة الإجابة دون درجة.' },
      ],
    },
  },
  contact: {
    en: {
      eyebrow: 'Support and feedback',
      title: 'Tell us what went wrong.',
      intro: 'Your message helps us make Muqabala easier and more useful.',
      sections: [
        { title: 'Report a problem', body: 'Tell us your phone or device, browser and language. Say where the problem happened. Do not send private answer details.' },
        { title: 'Share your opinion', body: 'Tell us if the feedback was clear and useful. Tell us what would make you practise again.' },
        { title: 'Personal interview coaching', body: 'Human coaching is separate from the app and may be offered through Inspire Ambitions. It is preparation only and does not guarantee a job.' },
        { title: 'Contact us', body: 'Send your message through the Inspire Ambitions contact page.', href: 'https://inspireambitions.com/contact/', linkLabel: 'Open the contact page' },
      ],
    },
    ar: {
      eyebrow: 'الدعم والملاحظات',
      title: 'أخبرنا ما الذي جعل التدريب صعباً.',
      intro: 'تساعد ملاحظات المرشحين مقابلة على تحسين الأسئلة ودعم اللغة والموثوقية والتفسيرات.',
      sections: [
        { title: 'الإبلاغ عن مشكلة تقنية', body: 'اذكر الجهاز والمتصفح واللغة والمرحلة التي حدثت فيها المشكلة والرسالة التي رأيتها. لا ترسل محتوى سرياً.' },
        { title: 'مشاركة رأيك في المنتج', body: 'أخبرنا هل كانت الملاحظات محددة وهل وثقت بها وما الذي سيجعلك تتدرب مرة أخرى.' },
        { title: 'تدريب شخصي للمقابلات', body: 'التدريب البشري منفصل عن التطبيق وقد يتوفر عبر إنسباير أمبيشنز. هو للاستعداد فقط ولا يضمن وظيفة.' },
        { title: 'طريقة التواصل', body: 'استخدم صفحة تواصل إنسباير أمبيشنز إلى أن تصبح قناة دعم مقابلة المخصصة جاهزة.', href: 'https://inspireambitions.com/contact/', linkLabel: 'افتح صفحة التواصل' },
      ],
    },
  },
  accessibility: {
    en: {
      eyebrow: 'Access without pressure',
      title: 'Practice should be easy to use.',
      intro: 'Muqabala works on phones and with a keyboard. It supports Arabic reading from right to left.',
      sections: [
        { title: 'Camera-free practice', body: 'Typing provides the same content feedback and avoids camera and microphone permissions.' },
        { title: 'Use a keyboard', body: 'You can use the main controls without a mouse. A clear border shows which control you chose.' },
        { title: 'Clear text and less movement', body: 'We use easy-to-read colours. We also reduce movement when your device asks us to.' },
        { title: 'Tell us about a problem', body: 'If anything is hard to see, hear, understand or use, tell us your device, browser and the page.' },
      ],
    },
    ar: {
      eyebrow: 'وصول دون ضغط',
      title: 'يجب أن يعمل التدريب لعدد أكبر من الناس.',
      intro: 'يُبنى مقابلة لاستخدام لوحة المفاتيح والتباين المقروء وتقليل الحركة واتجاه العربية والأجهزة المحمولة.',
      sections: [
        { title: 'تدريب دون كاميرا', body: 'توفر الكتابة نفس ملاحظات المحتوى وتتجنب أذونات الكاميرا والميكروفون.' },
        { title: 'لوحة المفاتيح والتركيز', body: 'يجب أن تبقى عناصر التحكم قابلة للاستخدام دون فأرة وأن تظهر مؤشر تركيز واضحاً.' },
        { title: 'الحركة والتباين', body: 'تحترم التجربة تفضيلات تقليل الحركة وتهدف إلى تباين ألوان WCAG AA.' },
        { title: 'الإبلاغ عن عائق', body: 'إذا كان أي جزء صعب الرؤية أو السماع أو الفهم أو التحكم، اذكر الجهاز والمتصفح والشاشة التي حدث فيها ذلك.' },
      ],
    },
  },
};
