import type { RoleKnowledge } from "./careers-data";

/**
 * Hospitality is a specialist lane inside the shared career coach. The role
 * names are intentionally broad and searchable; the free-text fields in the
 * wizard remain available when a hotel title is not listed.
 */
export const HOSPITALITY_ROLE_TITLES = [
  "Bell Attendant",
  "Concierge Agent",
  "Receptionist",
  "Guest Service Agent",
  "Reservations Agent",
  "Night Auditor",
  "Guest Relations Agent",
  "Front Desk Supervisor",
  "Duty Manager",
  "Assistant Front Office Manager",
  "Front Office Manager",
  "Rooms Coordinator",
  "Guest Experience Executive",
  "Guest Experience Manager",
  "Rooms Division Manager",
  "Director of Rooms",
  "Hotel Manager",
  "Resident Manager",
  "Room Attendant",
  "Laundry Attendant",
  "Housekeeping Coordinator",
  "Housekeeping Supervisor",
  "Assistant Executive Housekeeper",
  "Executive Housekeeper",
  "Director of Housekeeping",
  "Waiter",
  "Hostess",
  "Barista",
  "Bartender",
  "Banquet Server",
  "Restaurant Supervisor",
  "Assistant Restaurant Manager",
  "Restaurant Manager",
  "Banquet Manager",
  "Food and Beverage Manager",
  "Director of Food and Beverage",
  "Kitchen Steward",
  "Commis Chef",
  "Chef de Partie",
  "Junior Sous Chef",
  "Sous Chef",
  "Executive Sous Chef",
  "Executive Chef",
  "Revenue Coordinator",
  "Revenue Analyst",
  "Assistant Revenue Manager",
  "Revenue Manager",
  "Cluster Revenue Manager",
  "Director of Revenue",
  "Sales Coordinator",
  "Sales Executive",
  "MICE Sales Executive",
  "Assistant Sales Manager",
  "Sales Manager",
  "Director of Sales",
  "Commercial Director",
  "Marketing Coordinator",
  "Social Media Executive",
  "Digital Marketing Executive",
  "Marketing Manager",
  "Director of Marketing",
  "Accounts Clerk",
  "Income Auditor",
  "Cost Controller",
  "Finance Supervisor",
  "Financial Controller",
  "Director of Finance",
  "HR Coordinator",
  "Training Coordinator",
  "HR Officer",
  "Assistant HR Manager",
  "HR Manager",
  "Learning and Development Manager",
  "Director of HR",
  "Engineering Helper",
  "Technician",
  "AC Technician",
  "Electrician",
  "Plumber",
  "Engineering Supervisor",
  "Assistant Chief Engineer",
  "Chief Engineer",
  "Director of Engineering",
  "IT Support Agent",
  "Systems Coordinator",
  "PMS Specialist",
  "IT Supervisor",
  "IT Manager",
  "Director of IT",
  "Spa Receptionist",
  "Spa Therapist",
  "Spa Supervisor",
  "Spa Manager",
  "Director of Spa",
  "Security Officer",
  "Security Supervisor",
  "Security Manager",
  "Director of Security",
  "Storekeeper",
  "Receiving Clerk",
  "Purchasing Coordinator",
  "Buyer",
  "Purchasing Manager",
  "Procurement Manager",
  "Operations Manager",
  "Executive Assistant Manager",
  "General Manager",
  "Cluster General Manager",
  "Area General Manager",
] as const;

export const HOSPITALITY_COUNTRIES = [
  "UAE",
  "Saudi Arabia",
  "Qatar",
  "Oman",
  "Bahrain",
  "Kuwait",
  "Maldives",
  "Cruise lines",
  "United Kingdom",
  "United States",
  "India",
  "Philippines",
  "Other",
] as const;

export const HOSPITALITY_GOALS = [
  { value: "next_promotion", label: "Get my next promotion" },
  { value: "department_change", label: "Move to another department" },
  { value: "better_pay", label: "Earn more" },
  { value: "better_hours", label: "Get better working hours" },
  { value: "international_move", label: "Move to another country" },
  { value: "senior_leadership", label: "Reach hotel leadership" },
  { value: "leave_hospitality", label: "Use my hotel skills in another industry" },
] as const;

export const HOSPITALITY_BARRIERS = [
  { value: "not_sure", label: "I do not know where to start" },
  { value: "experience", label: "I need experience or exposure" },
  { value: "qualification", label: "I do not have the qualification" },
  { value: "money", label: "Training costs too much" },
  { value: "time", label: "I do not have enough time" },
  { value: "language", label: "Language is holding me back" },
  { value: "confidence", label: "I lack confidence" },
  { value: "network", label: "I do not know the right people" },
  { value: "visa", label: "Visa or location limits me" },
] as const;

const MARKET_SALARY_NOTICE = [
  {
    stage: "Current role benchmark",
    range: "Check current local listings",
    note: "Pay changes sharply by country, property tier, service charge and accommodation package.",
    pct: 35,
  },
  {
    stage: "Next-step role",
    range: "Verify for your target market",
    note: "Compare at least five recent adverts and two recruiter conversations before negotiating.",
    pct: 55,
  },
  {
    stage: "Department head",
    range: "Property-specific band",
    note: "Team size, P&L responsibility and brand tier matter more than title alone.",
    pct: 78,
  },
  {
    stage: "Cluster or regional leadership",
    range: "Package-based compensation",
    note: "Base pay is only one part of the package; verify bonus, housing, schooling and travel.",
    pct: 100,
  },
];

const HOTEL_COMMUNITIES = [
  "Hospitality industry groups in your city",
  "Hotelier Middle East events and community",
  "HSMAI regional learning events",
  "Your hotel brand's internal mobility network",
];

const HOTEL_EVENTS = [
  "Hotel Show and hospitality trade events in your target market",
  "Brand training and cross-property task-force opportunities",
  "Local hospitality recruitment and networking events",
];

function target(
  role: string,
  aliases: string[],
  skills: RoleKnowledge["coreSkills"],
  difficultyBase: number,
  planB: string,
  dayInLife: RoleKnowledge["dayInLife"],
): RoleKnowledge {
  return {
    role,
    aliases,
    coreSkills: skills,
    courses: [
      {
        name: "Hotel revenue and commercial fundamentals",
        provider: "HSMAI, AHLEI or a recognised local provider",
        cost: "Verify current provider price",
        duration: "4–12 weeks",
        rating: "Provider check required",
        why: "Commercial knowledge helps almost every supervisor or manager make stronger decisions.",
        badge: "Useful across departments",
        minBudget: 500,
      },
      {
        name: "Employer-led hotel systems shadowing and training",
        provider: "Your employer or the system trainer they approve",
        cost: "$0 when your employer provides access",
        duration: "2–6 weeks",
        rating: "Role-specific",
        why: "Ask for supervised access first. Evidence that you can use the system matters more than a generic certificate.",
        badge: "Ask your employer first",
        minBudget: 0,
      },
      {
        name: "Supervisory and people-leadership training",
        provider: "AHLEI, employer academy or recognised local provider",
        cost: "Verify current provider price",
        duration: "4–12 weeks",
        rating: "Provider check required",
        why: "Best when paired with a real shift, project or team responsibility.",
        minBudget: 500,
      },
    ],
    salary: MARKET_SALARY_NOTICE,
    communities: HOTEL_COMMUNITIES,
    people: [
      "Two department heads in your current or target hotel brand",
      "One recruiter who specialises in hospitality",
      "One operator doing the target role in your destination country",
    ],
    events: HOTEL_EVENTS,
    dayInLife,
    demand: "Demand varies by country, season, property openings and department. Verify with recent local vacancies before making a move.",
    difficultyBase,
    planB,
    frameworks: [
      "STAR examples using guest, revenue, cost, quality and team results",
      "A 90-second story connecting your current hotel experience to the target role",
      "A one-page promotion case with evidence, gaps and a 90-day action plan",
    ],
  };
}

export const HOSPITALITY_TARGETS: RoleKnowledge[] = [
  target(
    "Front Office Manager",
    ["front office", "front desk manager", "duty manager", "guest services manager"],
    [
      { skill: "Guest recovery and service leadership", priority: "high", how: "Document three difficult guest cases, the action you took and the measurable outcome." },
      { skill: "OPERA or property-management systems", priority: "high", how: "Ask for supervised access to reporting, profiles, inventory and night-audit workflows." },
      { skill: "Shift and people leadership", priority: "high", how: "Lead briefings, coaching and one service-improvement project with a tracked result." },
      { skill: "Rooms revenue and upselling", priority: "medium", how: "Track upgrade conversion, ADR or upsell value for one month and explain what changed." },
      { skill: "Quality and audit standards", priority: "medium", how: "Own one brand-standard or guest-feedback improvement cycle." },
      { skill: "Cross-department communication", priority: "medium", how: "Join a rooms, housekeeping or revenue project and record your contribution." },
    ],
    4,
    "Reservations, guest experience, training or hotel-systems roles reuse much of the same experience with less front-desk pressure.",
    [
      { time: "8:00", activity: "Review occupancy, VIPs, incidents and staffing before the morning briefing" },
      { time: "9:00", activity: "Coach the team and resolve escalated guest or operational issues" },
      { time: "11:00", activity: "Work with housekeeping and revenue on room readiness and inventory" },
      { time: "14:00", activity: "Review guest feedback, upselling and service-recovery patterns" },
      { time: "16:00", activity: "Prepare the next shift and follow up on people or quality actions" },
    ],
  ),
  target(
    "Revenue Manager",
    ["revenue", "revenue analyst", "reservations", "commercial strategy", "distribution"],
    [
      { skill: "Forecasting and demand analysis", priority: "high", how: "Build a weekly forecast from occupancy, pace, events and competitor signals." },
      { skill: "Excel and hotel reporting", priority: "high", how: "Practise lookups, pivots and a simple hotel performance dashboard." },
      { skill: "Pricing and inventory decisions", priority: "high", how: "Shadow one revenue meeting and write down the decision, evidence and outcome." },
      { skill: "Distribution channels", priority: "medium", how: "Learn how rates and inventory move through the PMS, channel manager, GDS and OTAs." },
      { skill: "Commercial communication", priority: "medium", how: "Present one recommendation in plain language to sales, rooms and finance." },
      { skill: "Market research", priority: "medium", how: "Track a comp set and local demand calendar for four weeks." },
    ],
    6,
    "Reservations, distribution, commercial analyst or sales-operations roles are practical bridges into revenue.",
    [
      { time: "8:30", activity: "Check pickup, pace, cancellations and yesterday's performance" },
      { time: "10:00", activity: "Update the forecast and investigate unusual demand movement" },
      { time: "12:00", activity: "Meet sales and rooms to align pricing, groups and inventory" },
      { time: "14:00", activity: "Review channels, restrictions and competitor positioning" },
      { time: "16:00", activity: "Document decisions and prepare the next trading action" },
    ],
  ),
  target(
    "Food and Beverage Manager",
    ["f&b manager", "restaurant manager", "outlet manager", "banquet manager", "food and beverage"],
    [
      { skill: "Outlet operations and service control", priority: "high", how: "Own one shift plan and measure service time, complaints and recovery." },
      { skill: "Food cost and labour control", priority: "high", how: "Review weekly cost, wastage and payroll figures with the outlet leader." },
      { skill: "People leadership", priority: "high", how: "Coach two team members and record the performance change." },
      { skill: "Hygiene and safety systems", priority: "high", how: "Complete role-relevant food-safety training and lead one audit correction." },
      { skill: "Menu and revenue thinking", priority: "medium", how: "Analyse item mix, average spend and one upselling experiment." },
      { skill: "Events and stakeholder coordination", priority: "medium", how: "Support one banquet or event from briefing to post-event review." },
    ],
    5,
    "Events, catering sales, supplier sales or training roles preserve your F&B knowledge while changing the working rhythm.",
    [
      { time: "9:00", activity: "Review bookings, staffing, stock, events and yesterday's numbers" },
      { time: "11:00", activity: "Walk the operation, coach supervisors and solve service risks" },
      { time: "13:00", activity: "Review costs, purchasing or menu performance" },
      { time: "16:00", activity: "Lead the pre-service briefing and check high-risk details" },
      { time: "19:00", activity: "Monitor peak service, guest feedback and team performance" },
    ],
  ),
  target(
    "Executive Chef",
    ["executive chef", "head chef", "sous chef", "chef"],
    [
      { skill: "Kitchen leadership and standards", priority: "high", how: "Lead briefing, quality checks and corrective coaching on a live service." },
      { skill: "Food cost and menu engineering", priority: "high", how: "Cost ten dishes and identify one margin or waste improvement." },
      { skill: "Food safety and compliance", priority: "high", how: "Own one HACCP or local food-safety control from record to correction." },
      { skill: "Production planning", priority: "high", how: "Build a forecast-led prep and staffing plan for one busy period." },
      { skill: "Supplier and purchasing judgement", priority: "medium", how: "Join a supplier review and compare quality, yield, price and reliability." },
      { skill: "Concept and guest insight", priority: "medium", how: "Develop and test one dish or menu change using real guest feedback." },
    ],
    7,
    "Sous-chef leadership, central production, culinary training, supplier roles or food-business operations are credible adjacent routes.",
    [
      { time: "7:00", activity: "Review deliveries, production, staffing and food-safety records" },
      { time: "10:00", activity: "Taste, coach, solve quality issues and prepare for service" },
      { time: "13:00", activity: "Monitor service and respond to operational pressure" },
      { time: "15:00", activity: "Review food cost, wastage, purchasing and upcoming business" },
      { time: "17:00", activity: "Brief the evening team and check priority events or VIPs" },
    ],
  ),
  target(
    "Sales Manager",
    ["hotel sales", "sales manager", "corporate sales", "mice sales", "leisure sales"],
    [
      { skill: "Account development", priority: "high", how: "Build a target list and document five researched outreach conversations." },
      { skill: "Hotel product and market knowledge", priority: "high", how: "Create a concise property, comp-set and segment briefing." },
      { skill: "Negotiation and contracting", priority: "high", how: "Shadow one proposal or contract discussion and explain the trade-offs." },
      { skill: "CRM and pipeline discipline", priority: "medium", how: "Track leads, next actions, value and probability in a clean pipeline." },
      { skill: "Presentations and site inspections", priority: "medium", how: "Lead or rehearse a needs-led hotel presentation and site inspection." },
      { skill: "Commercial collaboration", priority: "medium", how: "Join a revenue meeting and connect one sales action to demand need." },
    ],
    5,
    "Sales coordination, events, reservations, business development or supplier sales are strong bridge roles.",
    [
      { time: "9:00", activity: "Review pipeline, need dates, account actions and incoming enquiries" },
      { time: "10:30", activity: "Client calls, prospecting or account reviews" },
      { time: "13:00", activity: "Prepare proposals, contracts or a site inspection" },
      { time: "15:00", activity: "Align with revenue, events and operations on conversion risks" },
      { time: "17:00", activity: "Update the CRM and set the next action for every active lead" },
    ],
  ),
  target(
    "HR Manager",
    ["hr manager", "human resources", "talent and culture", "people and culture", "learning and development"],
    [
      { skill: "Employee relations and fair process", priority: "high", how: "Study local employment rules and practise documenting a clear, evidence-based case." },
      { skill: "Recruitment and workforce planning", priority: "high", how: "Build a hiring plan for one department using turnover and business need." },
      { skill: "Learning and performance", priority: "high", how: "Design one short training intervention and measure whether behaviour changed." },
      { skill: "Payroll and HR systems", priority: "medium", how: "Learn the core employee-data, attendance and reporting workflows used by your employer." },
      { skill: "Manager coaching", priority: "medium", how: "Practise turning a people problem into clear options, actions and follow-up." },
      { skill: "Confidential communication", priority: "high", how: "Use concise, neutral records and separate facts, allegations and decisions." },
    ],
    5,
    "HR coordination, recruitment, training, payroll or employee-experience roles are credible first steps.",
    [
      { time: "8:30", activity: "Review staffing, attendance, urgent cases and recruitment priorities" },
      { time: "10:00", activity: "Meet managers or employees on a people issue" },
      { time: "12:00", activity: "Work on hiring, onboarding, training or performance records" },
      { time: "14:30", activity: "Analyse turnover, staffing or engagement patterns" },
      { time: "16:00", activity: "Follow up actions, documentation and manager support" },
    ],
  ),
  target(
    "Chief Engineer",
    ["chief engineer", "director of engineering", "engineering manager", "hotel engineering"],
    [
      { skill: "Preventive maintenance planning", priority: "high", how: "Build or improve a weekly preventive-maintenance plan with completion evidence." },
      { skill: "Safety and statutory compliance", priority: "high", how: "Own one safety inspection, action log and verified close-out." },
      { skill: "Energy and cost control", priority: "high", how: "Track one utility or equipment-efficiency measure and quantify the result." },
      { skill: "Contractor and project management", priority: "medium", how: "Support a scoped repair or capital project from quotation to handover." },
      { skill: "Team and shift leadership", priority: "high", how: "Lead daily priorities, escalation and coaching for one operating period." },
      { skill: "Hotel operations judgement", priority: "medium", how: "Explain how engineering decisions affect guests, rooms, kitchens and business continuity." },
    ],
    6,
    "Engineering supervision, facilities, safety, energy management or specialist technical roles reuse most of the same preparation.",
    [
      { time: "7:30", activity: "Review alarms, incidents, plant readings and outstanding work orders" },
      { time: "9:00", activity: "Set team priorities and inspect high-risk equipment or guest-impact issues" },
      { time: "11:00", activity: "Coordinate contractors, projects or preventive maintenance" },
      { time: "14:00", activity: "Review safety, utility, cost and compliance records" },
      { time: "16:00", activity: "Update operations and prepare escalation cover for the next shift" },
    ],
  ),
  target(
    "Hotel General Manager",
    ["general manager", "hotel manager", "resident manager", "operations manager", "executive assistant manager"],
    [
      { skill: "Commercial and P&L leadership", priority: "high", how: "Own a forecast, budget or profit-improvement workstream with measurable results." },
      { skill: "Cross-department operations", priority: "high", how: "Lead a project spanning rooms, F&B, finance, sales and people." },
      { skill: "Owner and stakeholder communication", priority: "high", how: "Practise a one-page business update covering result, risk, action and decision needed." },
      { skill: "People and culture leadership", priority: "high", how: "Show evidence of succession, performance improvement and manager development." },
      { skill: "Guest, quality and brand strategy", priority: "medium", how: "Connect guest insight to one operational and financial improvement." },
      { skill: "Crisis and reputation management", priority: "medium", how: "Run a scenario review and document decisions, communication and recovery." },
    ],
    9,
    "Department-head, operations-manager, executive-assistant-manager or cluster specialist roles are the practical bridge to a GM seat.",
    [
      { time: "7:30", activity: "Review hotel performance, incidents, arrivals, events and immediate risks" },
      { time: "9:00", activity: "Lead the executive briefing and make cross-department decisions" },
      { time: "11:00", activity: "Owner, brand, commercial or people meetings" },
      { time: "14:00", activity: "Walk the operation and follow up guest, quality and team priorities" },
      { time: "16:30", activity: "Review financial outlook, decisions and tomorrow's critical actions" },
    ],
  ),
];

export function isHospitalityRole(value: string): boolean {
  const v = value.trim().toLowerCase();
  if (!v) return false;
  return HOSPITALITY_ROLE_TITLES.some((role) => role.toLowerCase() === v) ||
    HOSPITALITY_TARGETS.some((role) => role.role.toLowerCase() === v || role.aliases.some((alias) => v.includes(alias)));
}
